lib/patch/browser.js
lib/patch/geolocation.js
lib/patch/promise.js
test/patch/geolocation.spec.manual.js

@btford or @IgorMinar could you please review this PR.

refactor(Promise): simplify the code and add inline doc

---

test/microtasks.spec.js
test/patch/HTMLImports.spec.js
test/patch/MutationObserver.spec.js
test/patch/Promise.spec.js
test/patch/WebSocket.spec.js
test/patch/XMLHttpRequest.spec.js
test/patch/element.spec.js
test/patch/geolocation.spec.manual.js
test/patch/registerElement.spec.js
test/patch/requestAnimationFrame.spec.js
test/patch/setInterval.spec.js
test/patch/setTimeout.spec.js
test/util.js
test/util.spec.js
test/zone.spec.js

The goal is to ease the transition to supporting node.js env
@IgorMinar @btford please review

test: remove most references to window

---

lib/patch/browser.js
lib/patch/event-target.js
lib/patch/file-reader.js
lib/utils.js
test/patch/FileReader.spec.js

fix #137 
This PR is #174 rebased on master.
closes #136 #174

feat(lib/patch/file-reader): zone-binds FileReader#onEventName listeners

---

lib/patch/functions.js
test/patch/requestAnimationFrame.spec.js

fix(RequestAnimationFrame): pass the timestamp to the callback

---

README.md
dist/zone-microtask.js
lib/browser/zone-microtask.js

refactor: replace unicode characters with ASCII

---

package.json

chore(typings): publish TS typings in the npm distro

---

karma.conf.js
lib/patch/property-descriptor.ts
lib/patch/register-element.ts
lib/utils.ts
test/patch/WebSocket.spec.ts
test/ws-webworker-context.ts
test/zone_worker_entry_point.ts

I manually verified that this works in node, but we should have a way to automate this so we don't introduce the same bug in the future (see #258)
Closes #249

fix(WebWorker): Patch WebSockets and XMLHttpRequest in WebWorker

---

DEVELOPER.md
lib/browser/utils.ts
package.json

This will make cross-site scripting errors go down for automated feature testing using Selenium or Protractor frameworks.
Also improved some documentation/scripting for tests.

Fixes XSS errors occurring in Firefox and WebDriver

---

lib/zone.ts

fix(zone): remove debugger statement

---

lib/browser/websocket.ts
test/browser/WebSocket.spec.ts

f25b087 doesn't patch well, so fixed and added tests.
Sorry :cry:

fix(WebSocket patch): fix WebSocket constants copy

---

lib/browser/property-descriptor.ts

fix(property-descriptor): do not fail for events without targets

---

README.md

Adapted the example in the README.md. It didn't work no more. 
With these changes, it should work as described underneath the example.

Fixed the home page example. Now it works as described below.

---

lib/common/timers.ts
test/common/setInterval.spec.ts
test/common/setTimeout.spec.ts

Add ref/unref to timers for Node.js

---

lib/zone.ts

fix: use fetch(about://blank) to prevent exception on MS Edge

---

lib/zone.ts

fix(fetch): correct chrome not able to load about://blank

---

sauce.conf.js

Just enabling Edge on Saucelabs for now

WIP: add edge to sauce config

---

gulpfile.js
lib/zone-spec/async-test.ts
lib/zone-spec/fake-async-test.ts
lib/zone-spec/long-stack-trace.ts
lib/zone-spec/proxy.ts
lib/zone-spec/sync-test.ts
lib/zone-spec/wtf.ts
package.json

This means that we will stop polluting the global namespace when
zone.js is included.
Fixes #456

fix(bundling): switch to using umd bundles

---

README.md

perhaps we should create a FAQ?

docs(readme): add note about newrelic

---

lib/common/utils.ts
lib/mocha/mocha.ts
lib/node/events.ts
lib/zone.ts
package.json
test/browser/WebSocket.spec.ts
test/common/Error.spec.ts
test/common/Promise.spec.ts
test/common/setTimeout.spec.ts
test/main.ts
test/mocha-patch.spec.ts
test/node/Error.spec.ts
test/node/events.spec.ts
test/node/process.spec.ts
test/test-env-setup-mocha.ts
test/ws-webworker-context.ts
tslint.json

/ref https://github.com/angular/angular/issues/13311

Make sure there is no inner fn decl

---

scripts/sauce/sauce_connect_setup.sh

fix #544 to add reconnect options to avoid long time timeout in travis build

---

lib/common/utils.ts

Fix the formatting of the comment so that it's properly picked up by closure.

fix(closure): Fix closure error suppression comment.

---

lib/zone.ts
test/common/Error.spec.ts

This reverts commit ba7858cb3077e15f4291ce24cfbc8c8e2ab6b9c1.

Revert "fix: Correct ZoneAwareError prototype chain"

---

CHANGELOG.md

update CHANGELOG.md to 0.7.4

---

lib/common/utils.ts
lib/node/node.ts
test/node/process.spec.ts

refactor node, patch nextTick with patchMicroTask method.

refactor(node): patch nextTick with more general patchMicroTask method

---

README.md
STANDARD-APIS.md

Add standard API document to explain what apis has been patched with zone.js, it may related with #218.

docs(core): add standard api document

---

lib/browser/browser.ts
lib/common/utils.ts
lib/node/node.ts
test/browser/browser.spec.ts
test/node/process.spec.ts

in previous PR #627, I added a helper method findEventTask, this method should return a Task array, not a single EventTask.

fix(task): findEventTask should return Task array

---

lib/zone.ts

fix #638, remove debugger from zone.ts

fix(core): fix#638, remove debugger

---

STANDARD-APIS.md

fix a typo in STANDARD-APIS.md

docs: fix a typo in STANDARD-APIS.md

---

test/browser/browser.spec.ts

fix #718 
use asyncTestSpec to run Promise unhandle rejection test.

fix(test): fix #718, use async test to do unhandle promise rejection test

---

lib/browser/webapis-media-query.ts
lib/browser/webapis-notification.ts
lib/extra/bluebird.ts

load more modules (non standard api) into Zone with new load module methods.
1.  media query
2. notification
3. bluebird promise.

feat(patch): load non standard api with new load module method

---

MODULE.md
README.md

from v0.8.9, @mhevery refactor zone.js for better module management and better performance, and zone.js support `NOT` patch some APIs. So in this PR, we add documents for module system and how to disable features.

doc(module): add document for new module system and how to disable features

---

NON-STANDARD-APIS.md

fix #793.
make bluebird doc sample code workable.

fix(doc): fix #793, fix confuse bluebird patch doc

---

lib/browser/browser.ts
test/browser/browser.spec.ts
test/test-util.ts

1. fix #696, patch HTMLCanvasElement.toBlob as MacroTask
2. provide `ifEnvSupportWithDone` help method.

feat(patch): fix #696, patch HTMLCanvasElement.toBlob as MacroTask

---

gulpfile.js
lib/closure/zone_externs.js
scripts/closure/closure_compiler.sh
tsconfig-esm.json
tsconfig.json

1. move `zone_externs.js` to `lib`
2. add gulp task to copy the `zone_externs.js` to `dist`.

refactor closure build

---

lib/browser/browser.ts
test/browser/browser.spec.ts

fix #833
patch IntersectionObserver if available.

feat(patch): fix #833, add IntersectionObserver support

---

lib/browser/property-descriptor.ts
test/assets/worker.js
test/browser/Worker.spec.ts
test/browser_entry_point.ts

fix https://github.com/angular/angular/issues/19334
`Worker` onProperties (`onerror`, `onmessage`) should also be patched.

fix(patch): Worker should patch onProperties

---

.travis.yml
lib/browser/property-descriptor.ts
lib/zone-spec/wtf.ts
lib/zone.ts
package.json

1. fix several format issue reported by `tslint`.
2. add tslint to `travis`.

fix(lint): add tslint to travis

---

NON-STANDARD-APIS.md

add more detailed readme for how to import zone-patch-electron.

doc(electron): add more detailed doc for zone-electron patch

---

lib/jasmine/jasmine.ts
lib/zone-spec/async-test.ts
lib/zone-spec/proxy.ts
test/zone-spec/async-test.spec.ts
test/zone-spec/proxy.spec.ts

fix 4 issues.
1. proxyZone should call onHasTask when change delegate
2. AsyncTestZoneSpec should only call `finishCallback` when the it is pure async.
3. jasmine internal `setTimeout` should not in zone.
4. AsyncTestZoneSpec doesn't handle `eventTask` correctly.
fix https://github.com/angular/angular/issues/22448, which can be described as the following code. (this issue will also bring some other issues), I have created several cases here, https://github.com/angular/angular/pull/22454/files.
I also created test cases in `zone.js` to simulate `@angular/core/async`.
```javascript
beforeEach(async(() => {
TestBed.configureTestingModule({
declarations: [
AppComponent
],
}).compileComponents();
}));
it('simple timeout', async(() => {
setTimeout(() => {
expect(true).toBe(true);
}, 200);
})); …
```

fix(proxy): proxyZone should call onHasTask when change delegate, async should call finish only when sync

---

test/jasmine-patch.spec.ts
test/mocha-patch.spec.ts
test/zone-spec/async-test.spec.ts
test/zone-spec/fake-async-test.spec.ts

Just add some test cases 
1. jasmine case return promise
2. mocha case return promise
3. AsyncTestZoneSpec return promise case.

test: add test cases for returning promise

---

README.md

Update YouTube video URL so that it jumps to the instant shown on the video preview image.

Update YouTube video link

---

doc/task.md

Few lines need to be re-phrased for better understanding.

docs: Re-phrase the lines for better understanding

---

lib/common/promise.ts

fix #1168.
remove unused `== null` code.

fix(lint): fix #1168, remove unused = null code

---

lib/zone-spec/long-stack-trace.ts
test/zone-spec/long-stack-trace-zone.spec.ts

fix #1195.
thanks @thekip posting the issue and the suggestions of how to fix this one.

spec: fix #1195, should create new taskData if using OPTIMIZED TASKDATA in event task

---

lib/zone-spec/fake-async-test.ts

@vikerman, please review, thanks!

feat: add an option __zone_symbol__disableDatePatching to allow disable Date patching.

---

lib/common/promise.ts
test/common/Promise.spec.ts

fix: remove finally definition from Promise interface, will use es2018.promise in the future

---

lib/common/fetch.ts
lib/zone-spec/long-stack-trace.ts

These fixes are needed to make Zone compile with closure with advanced
optimizations.

fix: closure related fixes

---

lib/browser/custom-elements.ts

@vikerman, please review, thanks!

element: fix #1209, check customElements is null or not

---

lib/browser/browser.ts
lib/browser/property-descriptor-legacy.ts
lib/browser/property-descriptor.ts

xhr: fix #1212, add XMLHttpRequest availability check to avoid error in service worker.
