angular/zone.js

zone.js
Relevant WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=134364
closes #42
=> fix(patchViaPropertyDescriptor): disable if properties are not configurable

zone.js
It's breaks JSC =) (https://github.com/WebKit/webkit/blob/54d94f54241efa7b4dab59c88ebf82fb342f4596/Source/JavaScriptCore/parser/Parser.cpp#L1169)
Closes #53
Closes #54
=> fix(zone.js): don't make function declaration in block scope

zone.js
Without this fix, zone.js creates infinite loops when running in
non-strict mode.
Closes: #57
=> fix(zone): keep argument[0] refs around.

zone.js
The problem with using strict mode for the entire files
is that it will propagate for the entire bundled files
if zones.js is concatenated with other code written in
the non-strict mode
=> fix: use strcit mode for the zone.js code only

test/patch/element.spec.js, zone.js
Fix a case where the event handler is not removed when the event handler
function is used to handle multiple events on the same element.
replaces #36:
- add an assertion in tests,
- + `delete _bound[eventName];`
/cc @btford @IgorMinar @mnmtanish
=> Fix removeEventListener patch

karma-browserify.conf.js, karma-microtasks.conf.js, karma.conf.js, test/microtasks.spec.js, test/patch/HTMLImports.spec.js, test/patch/MutationObserver.spec.js, test/patch/Promise.spec.js, test/patch/WebSocket.spec.js, test/patch/XMLHttpRequest.spec.js, test/patch/element.spec.js, test/patch/registerElement.spec.js, test/patch/requestAnimationFrame.spec.js, test/patch/setInterval.spec.js, test/patch/setTimeout.spec.js, test/setup-microtask.js, test/setup.js, test/util.js, test/util.spec.js, test/zone.spec.js
relates to #98 
Previously tests were using the generated JS files in `/dist` which means that we have to rebuild after any modification of source files (in `/lib`).
With this PR tests use the files in `/lib` and are automatically re-run when one of them is changed. This is a step towards not having to `gulp build` for each single commit but only for releases.
test: strengthen assertions & some cleanup.
=> feat(test): serve lib/ files instead of dist/

dist/long-stack-trace-zone.js, lib/patch/event-target.js, lib/patch/property-descriptor.js, sauce.conf.js, test/microtasks.spec.js, test/patch/WebSocket.spec.js, test/patch/XMLHttpRequest.spec.js, test/patch/element.spec.js
Minor fixes here and there to have all meaningful tests passing in IE9.
Also adds IE9, IE10 and IE11 to the list of browsers tested in SauceLabs.
=> feat(zone.js): support IE9+

lib/patch/browser.js, lib/patch/geolocation.js, test/patch/geolocation.spec.manual.js
fixes #113 
Tests pass locally however the spec is disabled because it requires to manually allow the geolocation (via a popup).
/cc @jeffbcross @btford
=> feat(geolocation): patch the API

karma-browserify.conf.js, karma-microtasks.conf.js, karma.conf.js, lib/patch/promise.js, test/assets/sample.json, test/patch/Promise.spec.js
=> feat(fetch): patch the fetch API

README.md, lib/patch/browser.js, lib/patch/functions.js, test/patch/requestAnimationFrame.spec.js
- Add custom patching function for repeating callback functions to
support requestAnimationFrame wrapping.
- Bind requestAnimationFrame callback functions to the current zone
unless it is the root zone.
- DRY up requestAnimationFrame spec file (to remove duplication across
browsers)
- Add test that verifies that when registering frame callbacks from
within a frame callback, the zone in which they execute remains
constant.
- Add test to verify the wrapper is tolerant of invalid arguments.
- Add note to readme about behavior of raf
=> feat(patch): support requestAnimationFrame time loops

lib/browser/browser.ts, test/browser/XMLHttpRequest.spec.ts
Avoid throwing an error if an XHR is aborted after it has already
been sent and completed (this throws no error in the browser,
and zones should not introduce a new error).
=> fix(xhr): XHR macrotasks allow abort after XHR has completed

lib/browser/browser.ts, lib/browser/define-property.ts, lib/browser/property-descriptor.ts, lib/browser/register-element.ts, lib/browser/utils.ts, lib/browser/websocket.ts, lib/jasmine/jasmine.ts, lib/zone-spec/async-test.ts, lib/zone-spec/long-stack-trace.ts, lib/zone-spec/wtf.ts, lib/zone.ts
Use const and let instead of var
And use semicolon in interface
=> use const and let instead of var

gulpfile.js, lib/zone-spec/sync-test.ts, test/browser_entry_point.ts, test/sync-test.spec.ts
Will throw an exception if any asynchornous microtask or macrotask is scheduled. Allows event tasks to be scheduled.
=> feat(zonespec): add a spec for synchronous tests

gulpfile.js, lib/zone-spec/fake-async-test.ts, test/common_tests.ts, test/zone-spec/fake-async-test.spec.ts
This implementation is forked from the fake async from Angular 2 and adds the following
1) Implements own scheduler queue that doesn't depend on the jasmine implementation of a scheduler queue.
2) Handles errors in timer/microtask callbacks better so that pending timers are removed properly on error (No need for a clearPendingTimers at the end of a test handling errors). The queue processing is stopped after the first error and can be restarted.
3) Throw an exception if a XMLHttpRequest is used in a fakeAsync test - Useful for avoiding cases for ex. someone uses the online template compiler in a fakeAsync test but forgot to use the template cache and ends up doing a XHR in the test.
=> feat: Add a zone spec for fake async test zone.

lib/zone.ts
TypeScript 1.9 does better type inference on immediately evaluated
function expressions, which results in a type error.
Adding explicit any makes the current code behave the same in 1.8 and
1.9. A further change should add a more constrained type.
=> add explicit 'any' type

example/basic.html
The longStackTraceZoneSpec delegates the handling of the error to the zone. Without the changes I've made, the handling was passed to the 'root' zone which doesn't handle the error object. By adding a parentZone which handles the printing of the error in the 'onHandleError' hook, the full stack trace is visible.
=> Fixed the long stack trace example

lib/browser/browser.ts
Call cancelAnimationFrame instead of cancelMicroTaskAnimationFrame.
Fixes #326 and Leaflet/Leaflet#4588
=> fix(browser): patchTimer cancelAnimationFrame

lib/browser/define-property.ts, test/browser/define-property.spec.ts, test/browser_entry_point.ts
Fixes #391
The following code was failing in Chrome and Firefox (at least) when zone was loaded:
```
var someArray = [];
Object.defineProperty(someArray, 'length', {value: 2, writable: false})
```
I locally patched zone.js and was able to successfully run all Angular 2's tests with this fix. It solves the issues that were found in Chrome mobile 30 (Android 4.4.2).
=> fix(browser): make Object.defineProperty patch safer

lib/zone-spec/async-test.ts, test/zone-spec/async-test.spec.ts
When handling an error in the `AsyncTestZoneSpec`, instead of just passing the error message to the `_failCallback`, pass the actual error instance already available. This ensures that the complete stack trace is printed when logging a failed test.
Closes #379
=> Pass actual error to failCallback

lib/common/utils.ts
=> fix(patchProperty): return null as the default value

lib/zone.ts
ZoneAwarePromise does not technically implement or inherit the static
side of Promise, so aggressive optimizers may drop static methods such
as `all`, `race`, `reject`, and `resolve`.
This change explicitly exports them into quoted properties, which is
harmless for normal use and protects users of more aggressive
optimizers, such as Closure Compiler in typed mode.
=> fix(promise): support more aggressive optimization.

gulpfile.js, lib/nativescript/nativescript.ts, lib/zone.ts, package.json, test/nativescript_entry_point.ts
The [nativescript-angular](https://github.com/NativeScript/nativescript-angular/) mobile renderer was using the zone-node.js bundle until 0.6.18+ added patching for the `timers` module and `fetch` promise-likes. Those are incompatible with NativeScript and cause runtime errors. The best solution to support zone.js in NativeScript in a way that minimizes future breakage seems to involve creating a separate bundle.
I based this bundle on the node one, just removing the unsupported patches. I also added a rudimentary test task that runs under node (to avoid spinning up device emulators and complicate build infrastructure).
`nativescript-angular` vendors the `zone-nativescript.js` bundle that this PR adds, but it would be great if we get rid of that in the future.
This PR takes care of #437 …
=> Add a nativescript zone implementation

lib/node/events.ts, test/node/events.spec.ts
Fixes #470 by returning self from `addListener`, `on`, `prependListener`, `removeListener` in Node.js.
=> fix: fluent interface for EventEmitter

lib/browser/event-target.ts
Closes https://github.com/angular/zone.js/issues/468
WebSocket is an EventTarget descendant and should therefore also be patched for browsers (like IE11) that don't have EventTarget.
=> Add WebSocket to the NO_EVENT_TARGET list to be patched as well

lib/zone.ts, test/common/Promise.spec.ts
Hi,
Here is my proposed fix for #494. I've opted to check for the properties "__zone_symbol__state" and "__zone_symbol__value". It just occurred to me that checking the `constructor` might also work, but I am not sure. Commit message below.
Thanks,
Mark
---
`resolvePromise` assumes that if a value is an `instanceof` ZoneAwarePromise then it has the properties "__zone_symbol__state" and "__zone_symbol__value" and it _is_ a true ZoneAwarePromise; however, a user can construct a value that breaks this assumption by inheriting from ZoneAwarePromise without actually having those properties or being a true ZoneAwarePromise (for example, by attempting to subclass Promise).
We can fix this by adding checks for "__zone_symbol__state" and "__zone_symbol__value" to `resolvePromise`.
=> Make the check for ZoneAwarePromise more stringent

karma.conf.js, lib/browser/browser.ts, lib/zone.ts, test/browser-zone-setup.ts, test/common/Error.spec.ts, test/common/Promise.spec.ts, test/common_tests.ts, test/main.ts, test/ws-webworker-context.ts, test/wtf_mock.ts
feat(Error): Rewrite Error stack frames to include zone
The errors caused by the Zone contain extra stack frames. This feature
removes the confusing stack frames as well as appends the zone for each
stack frame to get a better understanding of the error messages.
Improved Error:
```
Error.spec.js:54 Error: Inside [InnerZone]
at insideRun (Error.spec.js:31) [InnerZone]
at Zone.run (zone.js:100) [<root> => InnerZone]
at testFn (Error.spec.js:29) [<root>]
at Zone.run (zone.js:100) [ProxyZone => <root>]
at Object.eval (Error.spec.js:19) [ProxyZone]
```
Original Error:
```
Error.spec.js:53 Error: Inside
at ZoneAwareError (zone.js:652)
at insideRun (Error.spec.js:31)
at ZoneDelegate.invoke (zone.js:216)
at Zone.run (zone.js:100)
at testFn (Error.spec.js:29)
at ZoneDelegate.invoke (zone.js:216) …
```
=> Better handling of stack traces in Zones

CHANGELOG.md, gulpfile.js, package.json
I added conventional changelog like you have on angular/angular, I added a gulp script and also a npm script for it.
I haven't hooked it up in the release process because I don't know how you want to do it (manually before a new release?).
I also fixed the install / gulp tsc so that it works on windows (I applied the same fix that you have on angular/angular).
And I regenerated the complete changelog.
=> docs(changelog): use conventional changelog

lib/browser/browser.ts, test/browser/XMLHttpRequest.spec.ts
1. in issue #287, the xhrhttprequest add documentreadychange eventlistener multipletimes (https://github.com/angular/zone.js/blob/master/lib/browser/browser.ts#L66), so when task finished, updateTaskCount will cause "More tasks executed then were scheduled" error. The issue
can be simplified as the following test case.
```javascript
Zone.current.fork({name:'test'}).run(function() {
var req = new XMLHttpRequest();
req.open('get', '/', true);
req.send();
req.onloadend = function() {
req.open('get', '/', true);
req.send();
}
```
So we should removeEventlistener before add new one.
2. another issue when xhrhttprequest call invalid url described in #530.
```javascript
var req = new XMLHttpRequest();
req.open('get', 'file:///test', true);
req.send();
```
=> fix bug add event listener to xhrhttprequest multiple times and invalid request call

lib/common/utils.ts
so 'isBrowser' will be true and 'propertyDescriptorPatch' will be executed correctly
closes #522
=> 'isNode' will now be false in nw.js environment

lib/zone.ts, test/common/Error.spec.ts
Fix #546, should keep error prototype chain correctly, in the original code, the ZoneAwareError will return a nativeError and lost the prototype chain
=> fix #546, should keep error prototype chain correctly

lib/common/utils.ts
now util.ts provide a patchEventTargetMethods to patch dom addEventListener and nodejs EventEmitter addEventListener method. 
becasue dom/node addEventListener has the similar signature. 
```javascript
addEventListener(eventName, handler, ...);
```
It is ok for dom element and node, but in other case, for example in PR #543, if we want to patch 
other eventTarget like MediaQuery , the add listener method signature is different 
```javascript
addListener(MediaQueryListListener listener);
```
So if we want to patch it, we need to write another patch logic like #543, it is not effective and in the future, if we want to patch other event Target like notification API like #536, we will need another same logic, so we need a generic way to patch event target like object.
In this PR, I provide  a …
=> add generic patch eventtarget method

lib/common/utils.ts, test/browser/browser.spec.ts
fix #525 and #540, inline event handler will not be patched with zone. And when you want to get the inline event handler will return null.
```javascript
<button id="btn1" onclick="func()">ok</button>
```
The func will not be patched, and if you access document.getElementById('btn1').onclick will return null.
The PR will not totally fixed the issue, if you don't access the elem.onclick for example, still no patch(but not null, you will get the original native version handler). you should add the following code to patch if you want to handle inline event handler
```javascript
var all = document.getElementsByTagName("*");
for (var i=0, max=all.length; i < max; i++) {
var elem = all[i];
for (var j = 0; j < eventNames.length; j ++) {
var attr = eventNames[j];
var attrValue = elem['on' + attr]; …
```
=> fix inline event handler issue #525 #540

README.md
Because zone.js patch global.promise, global.setTimeout and other API, so zone.js may conflict with other libs that also patch those API, in current README.md, we have warning about newrelic, we should also add async-listener, continuation-local-storage.
=> update README.md to add conflict explaination with other libs

sauce.conf.js, scripts/sauce/sauce_connect_setup.sh
fix #584, 
- because saucelabs announced that Android 4.0~4.3 will be [EOL](https://wiki.saucelabs.com/pages/viewpage.action?pageId=67012495
) so I remove those version from sauce lab test target.
- When test android 4.4 in sauce lab, there will be security waring pop up and let the test timeout, so we need to add --no-ssl-bump-domains options.
=> fix #584, remove android 4.1~4.3, add no-ssl options to make android 4.4 pass test

gulpfile.js, lib/browser/web-api.ts, test/browser/MediaQuery.spec.ts, test/browser_entry_point.ts
Based on the PR #543 and #549, I add a new file under lib/browser web-api.ts to patch mediaQuery, and other non-standard api later (for instance, notification API).
the patch in web-api will not be loaded by default, because those api are not supported by all browsers and versions, and it is difficult to tell whether the browser support it or not.  So user should load web-api.js by themselves. 
And because it is too difficult to test mediaQuery in jasmine,I only add the basic test case to see the prototype is patched or not.
=> add web-api.ts to patch mediaQuery

lib/zone.ts, test/common/zone.spec.ts
in issue #551, vaddin use zone.js and use JSON.stringify the dom element, because zone.js patched 
eventlistener, the JSON.stringify will serialize ZoneTask as well, and ZoneTask has reference to Zone, JSON.stringify(zoneTask) will cause cyclic error.
in this PR, I just leave the simplified information with toJSON() callback.
=> fix #551, add toJSON to ZoneTask to prevent cyclic error

lib/browser/property-descriptor.ts
fix #577, canPatchViaPropertyDescriptor test should add configurable to XMLHttpRequest.prototype.onreadystatechange, otherwise in opera 12, by default 
XMLHttpRequest.prototype.onreadystatechange,
so after test below.
```javascript
Object.defineProperty(XMLHttpRequest.prototype, 'onreadystatechange', {
get: function() {
return true;
}
});
```
XMLHttpRequest.prototype.onreadystatechange become non-configurable.
=> fix #577, canPatchViaPropertyDescriptor test break XHR prototype

lib/common/utils.ts, lib/node/fs.ts, test/node/fs.spec.ts
1. patch fs async methods (open, exists, write...) as macrotask, in previous patch, we use wrap, 
in my understanding, patch with wrap vs as macro task, we can both intercept schedule and invoke, 
but patch with macroTask can also have the ability to intercept cancelTask and hasTask.
2. add test cases of fs watcher related methods. Because we already patched EventEmitter, so fs.watch, fs.watchFile, fs.unwatchFile don't need additional patch. 
3. add a generic patch macro task method in util.ts
And in original patch, we patched the fs function with wrap, now we treat them as macrotask, so fs method will make additional callback (invokeTask/scheduleTask etc..) call, it may have some performance impact, I will make some other performance demo to check it.
=> patch fs methods as macrotask, add test cases of fs watcher

README.md, lib/zone.ts
Sorry I didn't check the format of my previous PR.
1. fix typo in comment of ZoneAwareError prepareStackTrace method.
2. reformat README.md
=> fix typo in comment and reformat README.md

test/common/setInterval.spec.ts
Fix #604, add a counter incase setInterval run more than once before setTimeout.
=> fix #604, sometimes setInterval test spec will fail on Android 4.4

lib/zone.ts, test/common/Error.spec.ts
fix #595,#427.
In previous PR to fix #546, we copy every property from NativeError to this (ZoneAwareError) with following logic.
```javascript
this[key] = error[key]
```
and such logic will have conflict with following angular2 BaseError logic.
```javascript
class BaseError extends Error {
/** @internal **/
_nativeError: Error;
constructor(message: string) {
super(message);
const nativeError = new Error(message) as any as Error;
this._nativeError = nativeError;
}
get message() {
return this._nativeError.message;
}
set message(message) {
this._nativeError.message = message;
}
get name() {
return this._nativeError.name;
}
get stack() {
return (this._nativeError as any).stack;
}
set stack(value) {
(this._nativeError as any).stack = value;
}
toString() {
return this._nativeError.toString(); …
```
=> fix #595, #427, #602, refactor ZoneAwareError property copy logic

lib/browser/property-descriptor.ts, lib/common/utils.ts, test/browser/XMLHttpRequest.spec.ts
Fix #593, the issue can be described as following case.
```javascript
var xhr = new XMLHttpRequest();
console.log('property', xhr.onreadystatechange);
```
When first time try to get xhr.onreadystatechange, it will access patched getter, and because 
canPatchPropertyDescriptor change the getter which always return true, so the logic will go to 
this.removeAttribute part which is not correct (this.removeAttribute is only for DOMElement).
=> fix #593, only call removeAttribute when have the method

lib/browser/define-property.ts, lib/common/utils.ts, lib/zone-spec/long-stack-trace.ts, lib/zone.ts
fix #607, sometimes uglifyjs will generate wrong code when our code like this.
```javascript
try {
doSomething();
} catch(e) {
errorHandling();
}
```
after uglifyjs, sometimes the code may become
```javascript
try {
doSomething();
} catch(e) {
e();
}
```
although use screwie8 option can resolve such issue, but to use another variable name other than 'e' is much safe.
=> fix #607 to change catch variable name to error/err

test/common/setInterval.spec.ts
setInterval will still fail sometimes in Android 4.4.
current spec is .
```javascript
let cancelId = setInterval(() => {
setTimeout(() => {
expect();
cancelInterval(cancelId);
});
}, 10);
```
Sometimes the interval will run twice before setTimeout, so two setTimeout will begin, and the expect in the second setTimeout will fail.
So in this PR, add a flag to make sure only one setTimeout run
=> fix test spec setInterval in android 4.4

lib/node/node.ts, test/node/crypto.spec.ts, test/node/http.spec.ts, test/node_tests.ts
1. Use patchMacroTask generic method to patch crypto randomBytes and pbkdf2 method.
and add test cases.
2. remove patch to http.ClientRequest, because in http.request(options, [cb]), the callback method is just a once listener which was added to req, so it has already been patched with EventEmitter patch.
=> patch crypto as macroTask and add test cases for crypto, remove http patch

dist/zone-mix.js, gulpfile.js, lib/browser/property-descriptor.ts, lib/browser/register-element.ts, lib/common/utils.ts, lib/mix/rollup-mix.ts
fix #533,  in electron/nw.js, we may need to patch both browser API and nodejs API, so we need a zone-mix.js to contains both patched API.
=> fix #533,  make a zone-mix to handle like electron/nw to patch browser and nodejs

lib/zone.ts, test/common/zone.spec.ts
add runOutsideOfCurrentZone method just like runOutsideAngular so we can run under rootZone or fork a new zone under rootZone.
```javascript
Zone.current.fork({name: 'testZone'}).run(function() {
Zone.runOutsideOfCurrentZone(() => {
expect(Zone.current.name).toEqual('<root>');
});
});
```
The motivation is to run some async code inside the zoneSpec's callback. Without the runOutsideOfCurrentZone method, such async call will cause infinite loop. 
for example:
```javascript
Zone.current.fork({
name: 'testZone', 
onScheduleTask: function(delegate, currentZone, targetZone, task) {
asyncLog(task);
return delegate.scheduleTask(targetZone, task);
}
});
```
asyncLog will cause infinite loop, now we can 
```javascript
Zone.current.fork({
name: 'testZone', 
onScheduleTask: function(delegate, …
```
=> add Zone.root to get root zone directly 

lib/common/timers.ts
fix #626, some browser/polyfill implements timer related methods, setTimer/setInterval/setImmediate/requestAnimationFrame were implemented to not return a valid handleId but undefined, it will cause zone.js throw error when check ref/unref.
=> fix(patch): fix #626, check timer patch return undefined

lib/browser/browser.ts, lib/common/utils.ts, lib/node/node.ts, lib/zone.ts, promise-adapter.js, test/browser/browser.spec.ts, test/node/process.spec.ts
1. add a flag to ignore consleError when uncaught promise error occurs, just like #614.
2. trigger unhandledrejection and rejectionhandled event handler in browser and nodejs env.
fix #621.
the spec can be found here.
- browser, https://developer.mozilla.org/en-US/docs/Web/Events/unhandledrejection
```javascript
window.addEventListener("unhandledrejection", function (event) {
console.warn("WARNING: Unhandled promise rejection. Shame on you! Reason: "
+ event.reason);
});
window.addEventListener("rejectionhandled", function (event) {
console.log("Promise rejected! Reason: " + reason);
});
```
- nodejs, https://nodejs.org/api/process.html#process_event_rejectionhandled
```javascript
process.on('unhandledRejection', (reason, p) => {
console.log('Unhandled Rejection at: Promise', p, …
```
=> feat(promise), fix #621, add unhandledRejection handler and ignore consoleError

lib/zone.ts, test/common/zone.spec.ts
the issue can be described as the following cases.
```javascript
const zone = Zone.current.fork({name: 'testZone'});
const task = zone.scheduleMacroTask('testPeriodTask', () => {
zone.cancelTask(task);
}, {isPeriodic: true}, () => {}, () => {});
task.invoke();
expect(task.state).toBe('notScheduled');
const task = zone.scheduleEventTask('testEventTask', () => {
zone.cancelTask(task);
}, null, () => {}, () => {});
task.invoke();
expect(task.state).toBe('notScheduled');
```
When task is cancelled in task's callback(running state), the runTask logic here https://github.com/angular/zone.js/blob/master/lib/zone.ts#L757 will reset the task's state to scheduled, so it will cause issues such as #638, updateTaskCount cause null error, because the task is cancelled but still in scheduled state.
=> fix(task): eventTask/Periodical task should not be reset after being cancelled when running

lib/common/utils.ts
in issue #618, sharepoint's code will create property on HTMLSpanElement like this
```javascript
oParent['_onmouseover'] = oParent.onmouseover;
```
and in zone.js 
https://github.com/angular/zone.js/blob/master/lib/common/utils.ts#L77
the inner property name is also startsWith '_'
```javascript
const _prop = '_' + prop; 
```
So this will cause a lot of problems. 
So we just use zoneSymbol to wrap the prop name.
=> fix(patch): fix #618, use zoneSymbol as property name to avoid name conflict

package.json
fix #649, use fixed version of typescript and clang-format @types/jasmine for now.
=> fix(package): fix #649, use fixed version typescript and clang-format

lib/browser/browser.ts
Fix #657.
The similar issue can be found here,https://bugs.chromium.org/p/chromium/issues/detail?id=159827
And some times the XMLHttpRequest will fire  onreadystatechange with readyState=4 multiple times.
```javascript
xhr.onreadystatechange = function() {
if (xhr.readyState === 4) {
if (xhr['ok']) {
console.log('error duplicate done');
}
xhr['ok'] = true;
}
}
```
this will cause ZoneTask to try to transit from notScheduled to running and cause error.
So I add a check to make sure ZoneTask is in scheduled state before running.
=> fix(xhr): fix #657, sometimes xhr will fire onreadystatechange with done twice

NON-STANDARD-APIS.md, dist/zone-bluebird.js, dist/zone-bluebird.min.js, gulpfile.js, lib/extra/bluebird.ts, test/extra/bluebird.spec.ts, test/node/Error.spec.ts, test/node_tests.ts
fix #455.
patch bluebird promise in zone and treat it as microTask,
add testcases for all bluebird APIs.
-usage, node
```javascript
require('zone-node.js');
const Bluebird = require('bluebird');
require('zone-bluebird.js');
Zone[Zone['__symbol__']('bluebird')](Bluebird);
```
- usage, browser
```javascript
<script src="zone.js"></script>
<script src="bluebird.js"></script>
<script src="zone-bluebird.js"></script>
<script>
Zone[Zone['__symbol__']('bluebird')](Promise);
</script>
```
We can simplify those steps to automatically patch Bluebird Promise, if global.Promise is Bluebird, but Bluebird maybe used just as a library (such as by sequelize), so I think patch it explicitly will be much safer.
=> feat(bluebird): patch bluebird promise and treat it as microtask

lib/common/timers.ts
Reference to task is not removed when timer's handler was faulty with exception. This can lead to memory leak.
=> fix(timers): cleanup task reference when exception

karma-build.conf.js, karma-dist.conf.js, lib/zone.ts, test/common/Error.spec.ts, test/custom_error.ts, test/node_entry_point.ts
fix #618, ZoneAwareError copy the Error's prototype properties , but not the properties of Error itself (static one)
for example, if other library define some custom function to Native Error
```javascript
Error.func = function() {}
```
then after zone.js patch Error, the func of Error will be lost.
in this PR, I also copy those properties from NativeError.
=> fix(error): fix #618, ZoneAwareError should copy Error's static properties as well

lib/zone-spec/long-stack-trace.ts, lib/zone.ts, test/zone-spec/long-stack-trace-zone.spec.ts
1. fix typo in longstacktrace
2. zone.js have longStackTraceSpec, it is very powerful, but it can't render handled promise rejection.
```javascript
const longStackTraceZoneSpec = Zone['longStackTraceZoneSpec'];
Zone.current.fork(longStackTraceZoneSpec).run(() => {
Promise p = new Promise((resolve, reject) => {
setTimeout(() => {
reject(new Error('Promise error'));
}, 10);
});
p.catch(error => console.log(error.stack);}
});
```
In this case, the error p.catch got is not a longStackTrace, because it is a handled promise rejection so it will not call longStackTraceSpec's onHandleError callback.
in this PR, I add a helper method in LongStackTraceZoneSpec, so if user want to render longStackTrace in promise.then/catch, user can call the method.
```javascript
const longStackTraceZoneSpec = …
```
=> feat(longStackTraceSpec): handled promise rejection can also render longstacktrace

lib/browser/browser.ts, test/browser/XMLHttpRequest.spec.ts
fix #671.
in safari, XMLHttpRequest.addEventListener is from XMLHttpRequestEventTarget not from EventTarget, so we should patch XMLHttpRequestEventTarget.
=> fix(XHR): fix #671, patch XMLHttpRequestEventTarget prototype

lib/zone.ts, test/common/Error.spec.ts, test/node/fs.spec.ts
1.zone.js patches most basic APIs, so when we want to debug, we will see a lot of zone related stack traces, for example, in example/basic.html, the simple event listener stack trace will look like this.
```
Error: aw shucks
at HTMLButtonElement.throwError (file:///Users/lijia/workspace/zone.js/example/basic.html:43:11) [long-stack-trace]
at Zone.runTask (file:///Users/lijia/workspace/zone.js/dist/zone.js:162:47) [<root> => long-stack-trace]
at HTMLButtonElement.ZoneTask.invoke (file:///Users/lijia/workspace/zone.js/dist/zone.js:356:33) [<root>]
-------------   Elapsed: 2483 ms; At: Sun Feb 12 2017 16:18:19 GMT+0900 (JST)   -------------  
at getStacktraceWithUncaughtError (file:///Users/lijia/workspace/zone.js/dist/long-stack-trace-zone.js:33:12) [long-stack-trace]
at new LongStackTrace …
```
=> feat(error): remove zone internal stack frames in error.stack

lib/zone.ts, test/common/Error.spec.ts
in phantomJS, the error.stack is readonly, so we need to catch such case and set the stack property directly to ZoneAwareError.
before 0.8.1, the case is OK because code here, https://github.com/angular/zone.js/blob/master/lib/zone.ts#L1955
and 
https://github.com/angular/zone.js/blob/master/lib/zone.ts#L1992
before 0.8.1 , the stackTraceLimit is 15, so in PhantomJS, ZoneAwareError can't finish finding all run/runGuarded/runTask, so stackRewrite is false, and ZoneAwareError will not try to override NativeError.stack.
and in 0.8.1, the stackTraceLimit increased to 100 in detect phase, so ZoneAwareError can find all run/runGuarded/runTask, so stackRewrite is true. 
In this PR, we just try/catch and write the zoneAware stack frames to ZoneAwareError directly
=> fix(error): fix #674, handle error.stack readonly case

lib/common/utils.ts
fix #667,
now we wrap the onProperty such as onclick, onsubmit with wrapFn, but wrapFn did not return the returnValue from eventHandler, currently we call event.preventDefault if the original eventHandler return false, but sometimes, user may need the return value to process other logic.
=> fix(event): fix #667, eventHandler should return result

test/jasmine-patch.spec.ts
add jasmine spec ifEnvSupport message
=> fix(jasmine): modify jasmine test ifEnvSupports message

lib/browser/property-descriptor.ts, test/browser/browser.spec.ts
fix #664, patch window, Document.prototype, SVGElement.prototype onProperties, such onclick, onresize, onload and so on.
=> feat(dom): fix #664, patch window,document,SVGElement onProperties

lib/browser/browser.ts, lib/browser/register-element.ts, lib/common/to-string.ts, lib/common/utils.ts, lib/node/node.ts, test/common/toString.spec.ts, test/common_tests.ts
fix #666 
after zone.js patch, function toString will look like 
```
function addEventListener(){return f(this, arguments)}
```
or other patched function. 
in this PR, we use the before patched delegate to output toString.
so function toString will look like 
```
function() {[native code]}
```
and will pass lodash isNative test.
=> fix(toString): fix #666, Zone patched method toString should like non patched

lib/common/utils.ts, test/webdriver/test.html, test/webdriver/test.js
fix #616, and https://github.com/mozilla/geckodriver/issues/515.
the issue just like https://github.com/angular/protractor/issues/2784.
In cross site contexts (such as WebDriver frameworks like Selenium), 
access eventHandler will throw permission denied error.
and in  https://github.com/angular/protractor/issues/2784, @juliemr fixed addEventListener, 
in #616, firefox will also call removeEventListener , the code can be found here, 
https://reviewboard.mozilla.org/r/98064/diff/12#index_header
so we need to do the same with addEventListener in removeEventListener to avoid 
such issue.
- And I modify a little about addEventListener/removeEventListener
https://github.com/JiaLiPassion/zone.js/blob/3fae05d347fde7e46cc8834158da74e544506877/lib/common/utils.ts#L320
in earlier fix, if …
=> fix(listener): fix #616, webdriver removeEventListener throw permission denied error

STANDARD-APIS.md, lib/browser/define-property.ts, lib/browser/property-descriptor.ts, lib/common/timers.ts, lib/common/utils.ts, lib/extra/bluebird.ts, lib/jasmine/jasmine.ts, lib/zone.ts, test/browser/WebSocket.spec.ts, test/browser/element.spec.ts, test/saucelabs.js, test/test-util.ts, test/zone-spec/long-stack-trace-zone.spec.ts, test/zone-spec/proxy.spec.ts
1. Fix all typos in source files
2. Remove extra semicolons after function definitions.
3. Fix some api doc of Zone.
=> fix(typo): fix typo, remove extra semicolons, unify api doc

lib/zone-spec/long-stack-trace.ts, lib/zone.ts, test/zone-spec/long-stack-trace-zone.spec.ts
fix #691.
in pervious modification, error.stack will be constructed in Error constructor, this will impact the performance of IE very badly, so in this PR, the auto-throw is removed.
fix #698.
when Error.stackTraceLimit is set to 0, the stack will be undefined, so we don't need to generate longstacktrace when stackTraceLimit = 0, it will improve performance in some test environment (such as some karma-test-shim for IE)
=> fix(error): remove throw in Error constructor to improve performance in IE11

.travis.yml, karma-build-sauce-selenium3-mocha.conf.js, karma-dist-sauce-selenium3-jasmine.conf.js, lib/zone-spec/long-stack-trace.ts, sauce-selenium3.conf.js, sauce.conf.js, test/browser/XMLHttpRequest.spec.ts
The list should be old browsers supported by Angular.
=> ci(SauceLabs): refresh browsers list

lib/zone.ts, test/browser/browser.spec.ts
fix #705,
don't json task.data(it has the target property) to prevent cyclic json error.
=> fix(task): fix #705, don't json task.data to prevent cyclic error

lib/zone.ts, test/common/zone.spec.ts
fix #405.
We often see that 'Zone.js already loaded' error, when we wrongly load zone.js twice, or load zone.js in some polyfill by incidentally. 
In this PR, we will try to throw the error message as 
```javascript
Zone already loaded. The loaded Zone.js script file seems to be path/to/zone.js(or some vender.bundle.js...)
```
So it will be easy to find out what is wrong, but it require the both zone.js to be upgrade to newer version (maybe 0.8.6)
=> fix(core): fix #405, refine the error message when zone.js already loaded

lib/common/utils.ts, test/browser/browser.spec.ts
fix #719 
In some browser, some of windows.onproperty, such as 
```
window.onerror = function() {
// this is undefined.
}
```
this is undefined, so when zone.js patch such property, should check if this is undefined and this is global , then use global insteadof this.
=> fix(patch): fix #719, window onproperty callback this is undefined

lib/common/utils.ts, test/common/util.spec.ts
when a property is non configurable , don't try to patch it.
=> fix(patch): fix #707, should not try to patch non configurable property

lib/zone.ts, test/common/zone.spec.ts
fix #706,
when zoneSpec's onHasTask throw error, should call handleError to let zoneSpec has chance to process the error.
=> fix(error): fix #706, handleError when onHasTask throw error

lib/zone.ts, test/common/Error.spec.ts
An idea to only throw one error to detect most zone stack trace frames.
=> feat(error): an idea for simple stack

.travis.yml, dist/zone_externs.js, package.json, scripts/closure/closure_compiler.sh, scripts/closure/closure_flagfile, test/closure/zone.closure.ts
1. add closure compiler externs file in dist/zone_externs.js
2. add test script in travis.
now we have 2 cases.
- normal case, can compile and keep the names defined in extern
- fail case, will throw error if the extern file is broken (definition error).
=> feat(closure): fix #727, add zone_externs.js for closure compiler

lib/common/utils.ts, lib/node/events.ts, test/browser/browser.spec.ts
fix #737 
add support to (Add)EventListenerOptions which has property 
```javascript
{
capture: boolean,
once: boolean,
passive: boolean
}
```
https://dom.spec.whatwg.org/#dictdef-addeventlisteneroptions
=> feat(EventListenerOptions): fix #737, add support to EventListenerOptions

lib/browser/browser.ts, lib/common/to-string.ts, lib/node/node.ts, test/common/Promise.spec.ts
fix #499, let 
```
object.prototype.toString(Promise.resolve())
```
active as native to output
```
[object Promise]
```
instead of current
```
[object Object]
```
in ES6, we can use Symbol.toStringTag, in ES5, I didn't find a better way to do this.
=> feat(patch): fix #499, let promise instance toString active like native

test/zone_worker_entry_point.ts
when test webworker websocket, the websocket is not closed, so it will cause ws-server crash sometimes when test in chrome or other environment which support websocket.
=> fix(test): fix websocket test server will crash when test in chrome

STANDARD-APIS.md, test/browser/registerElement.spec.ts
1. fix #725, in previous typo PR, forget to change the markdown table columns in STANDARD API document
2. fix a typescript compile warning in test/browser/registerElement.spec.ts
=> fix(doc): fix #725 in document, fix a typescript warning in test

lib/browser/property-descriptor.ts
Fix #708,
in jsdom, XMLHttpRequest has no onreadystatechange, 
in zone.js canPatchDescriptor logic, zone.js use a fake onreadystatechange descriptor which only have a getter, and XMLHttpRequest will use this one, and prevent set onreadystatechange property.
so we need to use a workable onreadystatechange descriptor in this case.
=> fix(patch): fix #708, modify the canPatchDescriptor logic when browser has no onreadystatechange

lib/browser/property-descriptor.ts, lib/common/utils.ts, test/browser/XMLHttpRequest.spec.ts, test/browser/browser.spec.ts
fix #746,fix #741 
1. #722 break #741, not patch onresize(maybe others), so I add it back in this PR
2. fix #746, check originalDescGet is null or not.
=> fix(patch): fix #746, check desc get is null and only patch window.resize additionally

lib/zone-spec/fake-async-test.ts, test/zone-spec/fake-async-test.spec.ts
The `flush` method advances time until all non-periodic timers
are cleared from the queue. It has a configurable limit (default 20)
of tasks that will be run before it gives up and throws an error,
in order to avoid infinite loops when polling timeouts are present.
Closes #735
=> Add a `flush` method to the FakeAsync zone spec

lib/common/promise.ts, lib/zone.ts, test/common/Promise.spec.ts
1. fix showError flag issue.
showError flag may change when drain microTask queue. So if we change the flag in one of the microTask, the flag will not be updated.
2. refactor parameter name in `promise.handleUnhandledRejection`
3. refactor showError, because we change the showError logic above, so maybe we provide 
`showUncaughtError()` in ZonePrivate is better. 
@mhevery, please review that ZonePrivate API change is ok or not. Thank you!
=> fix(showError): fix ignoreConsoleErrorUncaughtError may change during drain microtask

lib/zone-spec/fake-async-test.ts, test/zone-spec/fake-async-test.spec.ts
fix #760.
MicroTask callback may have additional arguments, 
such as 
```
process.nextTick(() => {...}, arg1, arg2);
```
fakeAsyncTestSpec should be able to send those `args(arg1, arg2)` to the original nextTick function
correctly.
=> fix(spec): fix #760, fakeAsyncTestSpec should handle microtask with additional args

lib/common/timers.ts
Older node versions (0.10, still default in debian stable) will throw exceptions while trying to use the objects returned nodes Timers implementation as keys -> don't make them try it.
For the same reason - as far as I understand it - this has never worked in node, also newer versions, anyway. Therefore this shouldn't break anything.
=> fix: don't save handleIds for node

lib/node/node.ts
1. fix #437, native script load timer module failed issue, if failed to load timer, just patch global.setTimeout
2. fix #744, in nodejs 0.10.x, global.setTimeout use timers.setTimeout but not equal, we should avoid to double patch the timer. We should check if global.setTimeout use timers.setTimeout but not equal, we only set __zone_symbol__ for consistency and then don't patch it at all in nodejs 0.10.x or other similar situation.
=> fix(timer): fix #437, #744, fix nativescript timer and  nodejs 0.10.x timer issue

lib/browser/browser.ts, lib/browser/webapis-media-query.ts, lib/browser/webapis-notification.ts, lib/common/utils.ts, lib/zone.ts
move `patchEventTargetMethod` and `patchOnProperties` help method from `Zone[__symbol__('patchEventTargetMethod')]` to `_ZonePrivate` api.
it will have type definition and much more clear structure.
=> refactor(private): move help method to _ZonePrivate

lib/zone.ts, test/common/task.spec.ts
fix #778.
In normal case, ZoneTask can only transit to `running` state from `scheduled` state.
But in some complex cases, ZoneTask will try to run after being canceled.
```javascript
var createInterface = require('readline').createInterface;
var Observable = require('rx').Observable;
require('zone.js');
var rl = createInterface({ terminal: true, input: process.stdin, output: process.stdout });
var keypress = Observable.fromEvent(rl.input, 'keypress');
var line = Observable.fromEvent(rl, 'line');
keypress.takeUntil(line).toPromise();
```
The case above describe such issue.
Be simplified, a `target` have `2` listeners for `1` event, and when the event trigger, the `1st` event listener remove the `2nd`, and then `2nd` listener run will cause this issue.
The detailed process is:
1. …
=> fix(task): fix #778, sometimes task will run after being canceled

lib/browser/property-descriptor.ts, lib/common/utils.ts, test/browser/XMLHttpRequest.spec.ts, test/browser/browser.spec.ts
related to #722.
We should try to patch onProperties with exact eventNames as possible.
in this PR, I separate the eventNames into several categories.
1. globalEventHandlerEventNames, eventNames in [GlobalEventHandlers](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers)
2. documentEventNames, eventNames in [Document](https://developer.mozilla.org/en-US/docs/Web/API/Document)
3. window, eventNames in [Window](https://developer.mozilla.org/en-US/docs/Web/API/Window)
4. element, eventNames in [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element)
5. webgl, eventNames in [WebGlContextEvent](https://developer.mozilla.org/en-US/docs/Web/API/WebGLContextEvent)
6. form, eventNames in [FormElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement)
7. …
=> fix(closure): patchOnProperty with exact eventNames as possible

gulpfile.js, lib/browser/browser.ts, lib/browser/rollup-main.ts, lib/node/events.ts, lib/node/fs.ts, lib/node/node.ts, lib/node/rollup-main.ts, test/browser-zone-setup.ts, test/node_entry_point.ts
1. patch node's timer setTimeout with `node_timer` name
2. patch `fs` and `events` of nodejs with `Zone.__load_patch` function
3. make some modification for file structure, zone-node will also have a `rollup-main`, so we have a clear structure.
- common (toString, error, promise)
- browser
- node
- mix(electron)
=> fix(patch): fix #744, add namespace to load patch name

lib/browser/webapis-media-query.ts, lib/browser/webapis-notification.ts
a typo which will cause `meduaQuery` and `Notification` use wrong `_global` variable which will be undefined.
=> fix(patch): fix #791, fix mediaQuery/Notification patch use wrong global

NON-STANDARD-APIS.md, gulpfile.js, karma-build.conf.js, lib/browser/browser.ts, lib/extra/cordova.ts, lib/zone.ts, test/browser-zone-setup.ts, test/browser_entry_point.ts, test/extra/cordova.spec.ts, test/node_entry_point.ts, test/test_fake_polyfill.ts
1. patch cordova.exec success/error callback with Zone.wrap, and cordova.exec may not be async so I didn't patch it as a macroTask.
2. merge fake polyfill (`custom_error`, `fake_cordova`) into a single `test_fake_polyfill` file.
=> feat(patch): fix #758, patch cordova.exec success/error with zone.wrap

lib/browser/browser.ts, test/browser/XMLHttpRequest.spec.ts, test/test-util.ts, test/zone-spec/task-tracking.spec.ts
fix https://github.com/angular/angular/issues/17167,
zone.js will patch xhr, and add onreadystatechange internally,
this onreadystatechange just for invoke the xhr MacroTask, so it should
not trigger ZoneSpec's callback.
in this commit, use original native addEventListener/removeEventListener
to add internal onreadystatechange event listener.
```javascript
if (listener) {
// don't use patched removeEventListener
oriRemoveListener.apply(data.target, ['readystatechange', listener]);
}
const newListener = data.target[XHR_LISTENER] = () => {
if (data.target.readyState === data.target.DONE) {
// sometimes on some browsers XMLHttpRequest will fire onreadystatechange with
// readyState=4 multiple times, so we need to check task state here
if (!data.aborted && (XMLHttpRequest as …
```
=> fix(xhr): inner onreadystatechange should not use zoneAwareListener

lib/common/to-string.ts, test/common/toString.spec.ts
fix #802,
in ios 9, webkt `MutationObserver` is not a function, is a object, so in `zone.js` patched `Function.prototype.toString`, we should check the `native` object's type is `function` or `object`.
=> fix(toString): fix #802, fix ios 9 MutationObserver toString error

lib/zone-spec/fake-async-test.ts, test/zone-spec/fake-async-test.spec.ts
=> fix(spec): fakeAsyncTestSpec should handle requestAnimationFrame

lib/common/promise.ts
remove duplicate console.log  when unhandled promise error occurs.
=> fix(promise): fix #806, remove duplicate console.log

lib/common/utils.ts
Some refactor.
1. replace `zoneSymbol` in util.ts to `Zone.__symbol__`, so we will only have one version of `Zone Symbol` method.
2. rename `findEventTask` method to `findEventTasksByEventName`
=> refactor(util): replace zoneSymbol with Zone.__symbol__

lib/zone-spec/fake-async-test.ts, test/zone-spec/fake-async-test.spec.ts
`flush()` in Angular's `fakeAsync` accepts a limit argument, which is passed to `FakeAsyncTestZoneSpec.flush()`
`flush()` on the `Scheduler` also accepts the limit argument. But `FakeAsyncTestZoneSpec.flush()` was not passing it along.
=> fix(spec): FakeAsyncTestZoneSpec.flush() passes limit along to scheduler

lib/browser/browser.ts, lib/browser/event-target.ts, lib/browser/property-descriptor.ts, lib/browser/websocket.ts, lib/common/events.ts, lib/node/events.ts, lib/zone.ts, test/common/Error.spec.ts, test/zone-spec/long-stack-trace-zone.spec.ts
fix #832.
fix #835.
- Task.data should not be a string but an object. 
- should define _global.
=> fix(task): fix #832, fix #835, task.data should be an object

lib/common/events.ts, test/browser/browser.spec.ts
fix #836.
1. The case can be described as,
```javascript
const listener1 = function() {
button.removeEventListener('click', listener1);
};
const listener2 = function() {
};
button.addEventListener('click', listener1);
button.addEventListener('click', listener2);
button.dispatchEvent(clickEvent);
```
in `listener1`, the listener will remove itself. so in the current implementation, `listener2` will not be invoked because tasks.length was reduced.
2. add test cases for similar cases, for example, in `listener1`, it will not remove itself, but remove other `listener` such as listener2.
=> fix(event): fix #836, handle event callback call removeEventListener case

lib/browser/browser.ts, lib/browser/event-target.ts, lib/browser/shadydom.ts, lib/browser/webapis-media-query.ts, lib/common/events.ts, lib/node/events.ts, lib/zone.ts, test/browser/browser.spec.ts
1. fix memory leak issue when addEventListener with {once: true}, in this PR, we handle `once` 
ourselves.
```javascript
button.addEventListener('click', function() {}, {once:true});
``` 
2.  if user don't call `eventTarget.removeEventListener` but call `zone.cancelTask` directly (for example, we may use like this in unit test spec to clean up eventListeners), we should clean the eventTasks from target.
```javascript
let eventTasks = [];
let zoneSpec = {
name: 'test',
onScheduleTask: function(task..) {
if (task.type === eventTask) {
eventTasks.push(task);
} 
}
}
zone.fork(zoneSpec).run(() => {
testCode();
});
// on finish clean up
function complete() {
eventTasks.forEach(task => {
task.zone.cancelTask(task);
});
}
```
3. add more test cases about `capture=true`. 
4. change ZonePrivate …
=> fix(event): fix memory leak for once, add more test cases

lib/zone-spec/fake-async-test.ts, test/zone-spec/fake-async-test.spec.ts
We added a new fature to FakeAsyncTestSpec to treat a
requestAnimationFrame as a timer with 16ms. However this breaks existing
Angular project tests because the RAF is reported as a pending timer at
the end of the test.
This change makes sure that existing Angular tests are not broken by not
counting RAF-s as pending timers at the end of a test.
=> fix(spec): do not count requestAnimationFrame as a pending timer

lib/node/node.ts, test/node/console.spec.ts, test/node_tests.ts
fix https://github.com/angular/angular/issues/17180
in nodejs, `console.log` will use `process.nextTick` and schedule a microTask which will cause 
infinite loop, so we need to make sure it run in `Zone.root`.
=> fix(console): console.log in nodejs should run in root Zone

lib/common/promise.ts
in `meteor` environment, `Promise.prototype.then` was defined as 
```javascript
{
writable: false,
configurable: true
}
```
so we can't patch it, we have to check if it is the case, we should change the writable to `true`.
=> fix(promise): fix #850, check Promise.then writable

lib/node/node.ts
The symbol doesn't exist when compiling node files stand alone.
=> "fix(node): remove reference to 'noop'"

lib/browser/websocket.ts, package.json
fix #862, fix wrong API usage for patchEventTarget of Websocket in old browsers.
=> fix(websocket), fix #862, in old safari, patchEventTarget for WebSocket use wrong API

lib/common/utils.ts, test/common/util.spec.ts
fix #859, `patchPrototype` should not patch `readonly`  property.
PropertyDescriptor
- `writable` === false
- only has getter.
will not be patched.
=> fix(patch): fix #859 readonly property should not be patched in patchPrototype

lib/zone-spec/fake-async-test.ts
This can be used to advance a secondary test scheduler like the Jasmine mock
Date every time flush advances to the next task to be processed.
=> feat(spec): add a 'tick' callback to flush()

lib/common/utils.ts, test/common/util.spec.ts
fix #869,
in safari , some method (Such as HTMLCanvasElement.prototype.toBlob) is `readonly`, when we try to patch it , it will throw error.
=> fix(patch): fix #869, should not patch readonly method

lib/browser/browser.ts, lib/browser/define-property.ts, lib/browser/property-descriptor.ts, lib/browser/websocket.ts, lib/common/error-rewrite.ts, lib/common/promise.ts, lib/common/timers.ts, lib/common/to-string.ts, lib/common/utils.ts, lib/extra/bluebird.ts, lib/extra/cordova.ts, lib/zone.ts, test/browser/browser.spec.ts, test/rxjs/rxjs.Observable.combine.spec.ts
1. we have use `global callback` in `EventTarget.addEventListener`, we should also use the same mechanism for `onProperty=listener` logic. We can use a global `wrapFn` instead of create a new function every time.
2. other small improvements, basically use `const string` to make sure not create too many strings.
3. Chrome 60 support `HTMLFrameSetElement.prototype.onmessageerror`, patch it.
=> feat(performance): onProperty handler use global wrapFn, other performance improve.

lib/zone-spec/fake-async-test.ts, test/zone-spec/fake-async-test.spec.ts
FakeAsyncTest Zone now just finds the last task currently in the timer queue
and tick-s till the endTime of that task.
Solves the issue when there is a short running setInterval in front of a
longer setInterval/setTimeout.
=> fix(spec): fix flush() behavior in handling periodic timers

lib/zone.ts
in zone.js we use native Promise when available to run microTaskQueue. in current version, we call 
```javascript
global[symbolPromise].resolve(0)[symbolThen](drainMicroTaskQueue);
```
so we will create a new native promise every time, in fact we only need to schedule a native async micro task to make sure drainMicroTaskQueue run async and run asap, we can reuse the promise for better performance.
```javascript
if (!nativeMicroTaskQueuePromise) {
if (global[symbolPromise]) {
nativeMicroTaskQueuePromise = global[symbolPromise].resolve(0);
}
}
if (nativeMicroTaskQueuePromise) {
nativeMicroTaskQueuePromise[symbolThen](drainMicroTaskQueue);
} ...
```
=> feat(performance): reuse microTaskQueue native promise

MODULE.md, lib/browser/browser.ts
can disable `requestAnimationFrame` patch with `__Zone_disable_requestAnimationFrame = true`
=> fix(module): fix #875, can disable requestAnimationFrame

lib/extra/cordova.ts
Cordova FileReader plugin wrap `FileReader` and have some possible bug,
https://issues.apache.org/jira/browse/CB-13179?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel&focusedCommentId=16127270#comment-16127270
and make `on_property`(such as onload) not being triggered.
So in this PR, add patch to make it work.
to use this patch, import `zone.js/dist/zone-patch-cordova` in your cordova project.
=> feat(cordova): fix #868, patch cordova FileReader

MODULE.md, karma-dist.conf.js, lib/browser/property-descriptor.ts, test/browser/browser.spec.ts, test/test_fake_polyfill.ts
fix #875.
can disable patch specified onProperties,for example,
if you want to disable `window.onmessage` and `HTMLElement.prototype.onclick` from zone.js patching,
you can do like this.
```
<script>
__Zone_ignore_on_properties = [
{
target: window,
ignoreProperties: ['message']
}, {
target: HTMLElement.prototype,
ignoreProperties: ['click']
}
];
</script>
<script src="../dist/zone.js"></script>
```
=> feat(onProperty): fix #875, can disable patch specified onProperties

NON-STANDARD-APIS.md, lib/rxjs/rxjs.ts, test/rxjs/rxjs.asap.spec.ts, test/rxjs/rxjs.spec.ts
fix https://github.com/angular/angular/issues/14316.
```javascript
const constructorZone: Zone = Zone.root.fork({
name: 'Constructor Zone',
onHandleError: (delegate: ZoneDelegate, currentZone: Zone, targetZone: Zone, error: Error) => {
log.push('error' + error.message);
const result = delegate.handleError(targetZone, error);
errorCallback && errorCallback();
return false;
}
});
let observable: any;
constructorZone.run(() => {
observable = Rx.Observable.of(1, 2, 3).observeOn(Rx.Scheduler.asap);
});
errorCallback = () => {
expect(log).toEqual(['erroroops']);
setTimeout(done, 0);
};
Zone.root.run(() => {
observable
.map((value: number) => {
if (value === 3) {
throw new Error('oops');
}
return value;
})
.subscribe((value: number) => {});
});
```
the case like this will reproduce the error, …
=> fix(rxjs): asap should runGuarded to let error inZone

lib/browser/browser.ts, lib/zone-spec/fake-async-test.ts, test/zone-spec/fake-async-test.spec.ts
Save the URL from xhr.open and log it when throwing an error from FakeAsyncTestZone when the XHR send it attempted. This would make it easier to debug such errors from a fakeAsync test.
=> feat(spec): log URL in error when attempting XHR from FakeAsyncTestZone

lib/common/utils.ts, test/browser/XMLHttpRequest.spec.ts
fix #886. 
fix #885.
fix https://github.com/angular/angular-cli/issues/7502.
patchOnProperties getter should return original listener.
the issue can be described as following code.
```javascript
const req = new XMLHttpRequest();
req.open('get', '/', true);
const listener = req.onreadystatechange = function() {
if (req.readyState === 4) {
done();
}
};
expect(req.onreadystatechange).toBe(listener);
req.onreadystatechange = function() {
return listener.apply(this, arguments);
};
req.send();
```
when try to get `onProperty listener` with such as `const listener = req.onreadystatechange`, should not return `wrapFn` but the real listener.
=> fix(patch): fix #886, #885, patchOnProperties getter should return original listener.

lib/browser/property-descriptor.ts, sauce-selenium3.conf.js, sauce.conf.js, test/browser/browser.spec.ts, test/browser/requestAnimationFrame.spec.ts, test/rxjs/rxjs.Observable.audit.spec.ts, test/rxjs/rxjs.Observable.concat.spec.ts, test/rxjs/rxjs.Observable.default.spec.ts, test/rxjs/rxjs.Observable.window.spec.ts
1. Update following browser version to latest 
- add Edge 15.15063
- add Android 6.0, 7.1 
- add Firefox 54 (55 failed to start in saucelabs)
- add Chrome 60
- add Safari 10
2. currently sacuelabs failed to start Safari 10 on macOS 10.12, so I use `chrome` to test `selenium 3.x` version.
3. In saucelabs, Safari 9 on ios 9.3 is unstable when run test about `rxjs.interval`, so I comment out some test cases about `rxjs`
4. in new `Edge 15` and `Chrome 60`, DOM API has some new `onProperties`, patch them as well.
=> update saucelabs config to latest version

lib/common/timers.ts, test/common/setInterval.spec.ts, test/common/setTimeout.spec.ts, test/zone-spec/fake-async-test.spec.ts, test/zone-spec/task-tracking.spec.ts
fix #314 
in browser and nodejs, `setTimeout`, `setInterval` should return original `timerId` (number or Timer object) instead of `ZoneTask`, because it will break some logic if other libraries expect the standard data types.
=> fix(timer): fix #314, setTimeout/interval should return original timerId

gulpfile.js, package.json, test/common/Promise.spec.ts, tsconfig-esm-node.json, tsconfig-node.json
fix #892 
1. upgrade to `typescript` 2.3.4 (current `angular` version)
2. set `downlevelIteration` to true in `tsconfig` when building `zone-node.js` to compile `for..of` which can handle `generators`.
travis build failed because `saucelabs` failed to start `safari 10` on `macOS 10.12`, so it will be passed after #896  to be merged.
=> feat(compile): fix #892, upgrade to typescript 2.3.4, support for...of when build zone-node

karma-base.conf.js, karma-dist-sauce-jasmine.conf.js, lib/common/promise.ts, lib/zone.ts, sauce.conf.js, test/common/Promise.spec.ts, test/common/zone.spec.ts, test/main.ts, test/rxjs/rxjs.Observable.combine.spec.ts
fix #898, #891, #783 
currently after loading `zone.js`, if we load some libraries which will override `global Promise`, `Zone.assertZonePatched` will throw error, and `angular` will not started. 
Sometimes we use 3rd party libraries and hard to control the load orders. So we need a better way to handle this process.
in this PR.
1. patch `global.Promise` with a setter by using Object.defineProperty , so after loading `zone.js`, if a new Promise want to override `global.Promise`, it will not update the `global.Promise`, but update the underlying `NativePromise`, so the whole process will be:
- before loading `zone.js`, `NativePromise` is Browser built in Promise.
- load `zone.js`, global.Promise is `ZoneAwarePromise`, global[symbolPromise] is `NativePromise`.
- after loading `zone.js`, set …
=> fix(promise): can set native promise after loading zone.js

lib/browser/browser.ts, lib/browser/event-target.ts, lib/common/events.ts, test/browser/browser.spec.ts
should handle `event.stopImmediatePropagation`, so if multiple listeners was added, one listener call event.stopImmediatePropagation, the remaining listeners should not be invoked.
=> fix(event): should handle event.stopImmediatePropagration

DEVELOPER.md, MODULE.md, NON-STANDARD-APIS.md, README.md, STANDARD-APIS.md, lib/closure/zone_externs.js, lib/zone.ts
I was reading the API documentation and stumbled across a few grammar mistakes and typos. I took the opportunity to fix these as well as a few formatting discrepancies!
=> docs: fix grammar and spelling mistakes

lib/common/events.ts, lib/common/utils.ts, test/browser/browser.spec.ts, test/test-util.ts
in samsung tv, the `SourceBuffer.addEventListener` will pass a `null this` in event handler.
we should handle this case by checking if `this` is null, we should use `event.target`.
=> fix(event): EventTarget of SourceBuffer in samsung tv will have null context

gulpfile.js, lib/browser/webapis-rtc-peer-connection.ts
fix #883.
in safari, when trigger RTCPeerConnection event handler `this` context is not the same with the event target when `addEventListener`.
```javascript
<html>
<head>
<script>
window.onload = function () {
console.log('Create RTCPeerConnection')
const pc = new RTCPeerConnection()
console.log('Add "track" event listener')
let event
pc.addEventListener('track', function(_event) {
console.log('this === pc', this === pc);
console.log('track event', _event);
event = _event
});
/*pc.ontrack = function(_event) {
console.log('this === pc', this === pc);
console.log('track event', _event);
event = _event
};*/
console.log('Dispatch "track" event')
pc.dispatchEvent(new Event('track'))
if (event) {
console.log('Success!')
} else {
console.error('Failure!')
}
}
</script>
</head>
</html>
```
in …
=> fix(event): fix #883, fix RTCPeerConnection Safari event not triggered issue.

lib/common/events.ts
The recent change in tsickle to handle @fileoverview comments in a transformer slightly changed our semantics, so the @fileoverview comment was getting lost.  A proper fix in tsickle is forthcoming.
=> Add newline to separate @fileoverview comment from a node.

lib/common/events.ts, lib/common/utils.ts
fix #911,
sometimes in `IE`, event handler will have an `undefined` event parameter.
we can use `window.event` in this case. 
https://developer.mozilla.org/en-US/docs/Web/API/Window/event
=> fix(event): fix #911, in IE, event handler event maybe undefined

lib/common/events.ts, lib/common/promise.ts, lib/zone.ts, tsconfig-esm.json
fix #891 
1. sometimes NativePromise will not be fully ready when override global.Promise, we should add check about it.
2. now by default, typescript 2.3 will compile `iterable` and `spread operator` with new polyfill code and will make `dist/zone.js` bigger, and we don't really have to use `iterable` and `spread`, so we use simple loop to reduce the `zone.js` size.
=> fix(promise): fix #891, sometimes NativePromise will not ready, and reduce zone.js size

lib/common/promise.ts, package-lock.json, package.json, tsconfig.json
Due to stricter generic type checks, signatures for ZoneAwarePromise
need to be changed. See
https://github.com/Microsoft/TypeScript/pull/16368
The signatures from lib.es5.d.ts were copied over for .then and .catch.
=> Upgrade to typescript 2.5.2

lib/browser/browser.ts, lib/common/utils.ts, test/browser/browser.spec.ts, test/common/util.spec.ts, test/test-util.ts
fix #925.
1. patch `navigator.getUserMedia(constraints, successCallback, errorCallback)` successCallback, errorCallback
2. provide a util method to patch function arguments.
=> fix(patch): fix #925, patch navigator.getUserMedia

lib/browser/define-property.ts, test/browser/define-property.spec.ts
fix #927.
should not throw error when defineProperty with frozen desc
=> fix(patch): fix #927, should not throw error when defineProperty with frozen desc

lib/jasmine/jasmine.ts
This lets us skip the ProxyZone if we really don't need it in our tests.
=> fix(jasmine): store original jasmine method

lib/common/timers.ts, package.json, test/browser/requestAnimationFrame.spec.ts, test/common/setInterval.spec.ts
fix #934.
`setInterval` will auto clear timerId  after  first time invoked.
the issue was imported several versions ago, but it doesn't become a problem because we 
return `ZoneTask` from `setInterval` before `zone.js 0.8.17`, from `zone.js 0.8.18` , `setInterval` will return the original `timerId`, so when we call `clearInterval` the `timerId` have been cleared, which will cause zone.js `onHasTask` not be called, the `setInterval` task was always there.
And will cause `ngZone` not stable.
Also fix `rxjs` version to `5.4.2` to avoid `karam` error, I will continue to figure out how to resolve `karam` test error with `rxjs 5.5.0`. 
The issue is here, and it seems it will be fixed in `rxjs 5.5.1`
https://github.com/ReactiveX/rxjs/issues/2971
=> fix(timer): setInterval should not auto cancel after callback invoked, fix rxjs version to pass CI

lib/zone-spec/fake-async-test.ts, test/test_fake_polyfill.ts, test/zone-spec/fake-async-test.spec.ts
fix #937 
let user be able to customize which macroTasks can be test with `fakeAsyncTestSpec`.
for example, in #937, user want to test `cavans.toBlob()`. with this PR, user can achieve it in two ways.
1. pass the options from `FakeAsyncTestSpec` constructor
```javascript
const testZoneSpec = new FakeAsyncTestZoneSpec('name', false, [{source: 'HTMLCanvasElement.toBlob'}]);
```
2. sometimes application test code can't access `FakeAsyncTestSpec` initialize process, so user can also define a global variable before load `fakeAsyncTest`.
- browser
```javascript
window['__zone_symbol__FakeAsyncTestMacroTask'] = [{
source: 'HTMLCanvasElement.toBlob',
callbackArgs: ['testBlobData']  // the test blob data which will be passed back to callback
}];
```
- Node
```javascript …
```
=> fix(fakeAsyncTest): fix #937, let user be able to customize testable macroTask

lib/mocha/mocha.ts
- `window` does not exist in NativeScript applications.
- this removes a hacky workaround where you assign `global.window` to `global` before including the mocha patch.
- preserve existing behavior by using window first if it exists.
=> fix(mocha): use global if window does not exist

lib/zone.ts
Without this extra star, the Closure commands in the jsdoc are ignored.
=> add missing star in zone jsdoc

README.md, package.json
This change adds an `unpkg` field to package.json that will allow users to load zone.js via https://unpkg.com/zone.js (i.e. w/out using the ?main=browser query parameter).
Also, just FYI, we're removing support for using the `browser` fallback on unpkg.com due to the fact that it was originally intended to be used by bundlers, which unpkg is not.
For more info, please see https://github.com/unpkg/unpkg/issues/63
=> Use bare unpkg URL

lib/common/events.ts
fix #956.
in some hybrid case, some part of application will under control by `zone`, some are not, so in patched `Event.prototype.stopImmediatePropagation` , we need to call native one.
=> fix(core): handle hybrid Event.prototype.stopImmediatePropagation

lib/common/events.ts
fix https://github.com/angular/angular/issues/20442
current `zone.js` optimized `event` keep a global `taskData` to pass some arguments inside, 
it should be cleared correctly to avoid memory leak.
=> fix(core): fix memory leak of event

lib/common/promise.ts, test/common/Promise.spec.ts
fix #955.
print better log when `uncaught promise error` occurs.
=> feat(promise): fix #955, print readable log when uncaught promise error

lib/common/events.ts, test/browser/browser.spec.ts
fix #930.
when listener was added outside of zone (before `zone.js` loaded), and it will not be able to `removed` after `zone.js` loaded. 
So we should always call `native` removeEventListener if we can't find eventListeners in zone kept task list.
=> fix(event): fix #930, should be able to remove listener added outside of zone

lib/common/events.ts, test/browser/browser.spec.ts
fix #969.
Should be able to access `target/eventName/capture` information when using `addEventListener` in `onScheduleTask` callback. 
in `onScheduleTask`.
```javascript
onScheduleTask: (parentZoneDelegate: ZoneDelegate, currentZone: Zone, targetZone: Zone,
task: Task): any => {
const target = (task.data as any).taskData.target;
const eventName = (task.data as any).taskData.eventName;
const capture = (task.data as any).taskData.capture;
return parentZoneDelegate.scheduleTask(targetZone, task);
}
```
in `onInvokeTask`, `onCancelTask`.
```javascript
onInvokeTask(
parentZoneDelegate: ZoneDelegate, currentZone: Zone, targetZone: Zone, task: Task,
applyThis: any, applyArgs: any) {
const target = (task as any).target;
const eventName = (task as any).eventName;
const capture = (task as …
```
=> fix(core): fix #969, should be able to access target/eventName info in onScheduleTask

STANDARD-APIS.md, lib/browser/browser.ts, lib/common/events.ts, test/browser/browser.spec.ts, test/test_fake_polyfill.ts
now `angular` blackList events work for 
- onProperty, such as `document.onscroll`
- HostListener, such as `  @HostListener('document:scroll')`
but not for `addEventListener` such as `document.addEventListener('scroll')`.
in this PR, I use `__zone_symbol__BLACK_LISTED_EVENTS` to also blacklist `addEventListener`.
=> fix(event): ignoreOnProperties also apply on addEventListener

lib/common/promise.ts, lib/zone-spec/long-stack-trace.ts, lib/zone.ts
fix #979.
- should not keep a non serializable `ZoneTask` on `error` when `Promise.reject`.
- and don't save the `ZoneTask` instead save the error stacks to avoid memory leak.
- only save the information when `longStackTraceZone` in there.
=> fix(error): fix #979, should not attach non serializable info on error

lib/common/utils.ts, test/browser/browser.spec.ts, test/test_fake_polyfill.ts
fix #978.
The issue can be described as 
1. before load `zone.js`, add handler to onprop, such as `elem.onload=function() {};`.
2. load `zone.js`.
3. clear, `elem.onload = null`. 
4. `elem.onload` is not cleared.
We need try to clear the `onprop` with the non-patched descriptor.
=> fix(core): fix #978, should be able to clear onhandler added before zone.js

NON-STANDARD-APIS.md, gulpfile.js, lib/browser/browser.ts, lib/common/utils.ts, lib/extra/electron.ts, lib/node/node.ts, lib/zone.ts
fix #537, fix #669.
add `electron` support.
- on event
- dialog
- shortcut
- menuitem
- app method, such as getFileIcon
- shell
- session
- desktopCapturer
...
there is a sample repo here.
https://github.com/JiaLiPassion/zone-electron
=> feat(electron): fix #537, #669, add electron support

lib/common/to-string.ts, test/common/toString.spec.ts
This PR complements PR #686 , making `Function.prototype.toString.toString()` also returns `"function toString() { [native code] }"`, which should be a little safer.
Update: `Function.prototype.toString.call(Function.prototype.toString)` will return `[native code]`, too.
=> add OriginalDelegate prop to Function::toString

NON-STANDARD-APIS.md, gulpfile.js, lib/extra/jsonp.ts
fix https://github.com/angular/angular/issues/7792
provide a helper method to patch `jsonp`.
Because jsonp has a lot of implementation, so
user need to provide the information to let json `send` and `callback` in zone.
sample usage is:
```javascript
import 'zone.js/dist/zone-patch-jsonp';
Zone['__zone_symbol__jsonp']({
jsonp: getJSONP,
sendFuncName: 'send',
onSuccessFuncName: 'onSuccess',
onFailedFuncName: 'onFailed'
});
```
now the CI failed because new version `jasmine` complains,  I have pinned the version of `jasmine` in #994.
=> feat(jsonp): provide a help method to patch jsonp

lib/browser/webapis-media-query.ts, test/test-env-setup-jasmine.ts
fix #998.
patch `mediaQuery` for new Safari.
=> fix(patch): fix #998, patch mediaQuery for new Safari

lib/browser/property-descriptor.ts
fix #1000.
check target prototype is available or not, in some browser with some extensions or 3rd party library installed, global object's prototype maybe modified.
=> fix(core): fix #1000, check target is null or not when patchOnProperty

gulpfile.js, lib/jasmine/jasmine.ts, lib/rxjs/rxjs-fake-async.ts, lib/zone-spec/fake-async-test.ts, test/zone-spec/fake-async-test.spec.ts
fix https://github.com/angular/angular/issues/8678
support `Date.now` in `fakeAsyncTest`. there are `3` features in this PR.
- support auto patch `Date.now` and `new Date()` in `fakeAsync`.
```javascript
fakeAsyncTestZone.run(() => {
const start = Date.now();
testZoneSpec.tick(100);
const end = Date.now();
expect(end - start).toBe(100);
});
fakeAsyncTestZone.run(() => {
const start = new Date();
testZoneSpec.tick(100);
const end = new Date();
expect(end.getTime() - start.getTime()).toBe(100);
});
```
- automatically run a `fakeAsync` test when `jasmine.clock().install` is called.
```javascript
beforeEach(() => {
jasmine.clock().install();
});
afterEach(() => {
jasmine.clock().uninstall();
});
it('should get date diff correctly', () => {  // we don't need fakeAsync here.
// automatically …
```
=> feat(jasmine): support Date.now in fakeAsyncTest

gulpfile.js, karma-dist.conf.js, lib/common/promise.ts, lib/testing/promise-testing.ts, lib/testing/zone-testing.ts, lib/zone-spec/async-test.ts, test/browser-zone-setup.ts, test/node_entry_point.ts, test/zone-spec/async-test.spec.ts
fix #1013.
currently if there are some `async` task which is not `zone aware`, `AsyncTestZoneSpec` will not handle it. such as, 
```javascript
it('test jsonp', () => {
let finished = false; 
const asyncTestZoneSpec = new AsyncTestZoneSpec(() => {
expect(finished).toBe(true);
}, () => {}, 'async');
asyncTestZone.run(() => {
jsonp(url, () =>{
// success callback
finished = true;
});
});
}); 
```
this case will fail because `jsonp` is not a `zone aware` async operation, so finished will be still be false, when `AsyncTestZone` think all `microTasks` and `macroTasks` have been done (but jsonp is still running).
We can't handle all `non zone aware` async task, so when such kind of issue occurs, we can help user use `Zone.prototype.scheduleMicroTask` or `Zone.prototype.scheduleMacroTask` to …
=> feat(test): can handle non zone aware task in promise within AsyncTestZoneSpec

gulpfile.js
- new version of `rollup` have deprecate `entry` key, use `input` instead
- add `external` key to specify `rxjs` library as external libs.
- format `gulpfile.js`
=> feat(rollup): use new rollup config to prevent warning

NON-STANDARD-APIS.md, gulpfile.js, lib/browser/webapis-resize-observer.ts, test/browser-zone-setup.ts, test/browser/browser.spec.ts
fix #1011.
patch `ResizeObserver`.
support one observer patch different HtmlElements in different zones.
```javascript
const observer1 = new ResizeObserver((entries: any, ob: any) => {
console.log('observer1 zone', Zone.current);
for (const entry of entries) {
console.log('observer1 resize entry target', entry.target);
console.log('observer1 resize entry size', entry.contentRect);
}
});
observer1.observe(div1);
observer1.observe(div2);
Zone.root.run(() => {
observer1.observe(div3);
});
```
full sample can be find here, https://github.com/JiaLiPassion/zone-resize-observer, 
only work in `Chrome 64`.
=> feat(patch): fix #1011, patch ResizeObserver

lib/zone-spec/fake-async-test.ts, test/zone-spec/fake-async-test.spec.ts
fix #1032 
Thanks @e-hein find this issue and provide the fix and spec.
`fakeAsyncTest` should pass `parameters` correctly.
=> fix(testing): fix #1032, fakeAsync should pass parameters correctly

lib/common/events.ts, test/node/events.spec.ts
fix #1021.
`EventEmitter.prototype.removeListener` and `EventEmitter.prototype.removeAllListeners`  should return `EventEmitter` itself to allow `chaining`.
=> fix(event): fix #1021, removeListener/removeAllListeners should return eventEmitter

.travis.yml, karma-build-sauce-selenium3-mocha.conf.js, lib/mocha/mocha.ts, test/zone-spec/async-test.spec.ts
fix https://github.com/angular/angular/issues/22150
in new version of mocha, the code like below 
```javascript
beforeEach(async(() => {
TestBed.configureTestingModule({
declarations: [
AppComponent
],
}).compileComponents();
}));
it(`should have as title 'app'`, async(() => {
console.log('title app test');
const fixture = TestBed.createComponent(AppComponent);
const app = fixture.debugElement.componentInstance;
expect(app.title).to.equal('app');
}));
```
will in the same `Mocha.Runner.prototype.run`.
so `Mocha.Runner.prototype.run` will run into `ProxyZone` instead of `rootZone`, we need to remove the `root zone` check, otherwise all mocha test will not begin.
also update `mocha` to 5.0.1
=> fix(test): fix mocha compatible issue

.travis.yml, gulpfile.js, lib/extra/bluebird.ts, package.json, test/extra/bluebird.spec.ts, test/node_bluebird_entry_point.ts, test/node_tests.ts, yarn.lock
fix #921, #977 
Support `bluebird`.
1. Support use `Bluebird` to override `global Promise`.
2. Support `Bluebird` 's own API to be considered as `microTask`.
3. fix #921 bug that all promises are run into the same zone.
=> feat(bluebird): fix #921, #977, support bluebird

lib/common/promise.ts, lib/zone.ts
fix #996.
Expose `UncaughtPromiseError` interface.
=> feat(core): fix #996, expose UncaughtPromiseError

lib/common/promise.ts
fix #946.
don't try to patch `Promise.prototype.then` when it is not configurable or writable
=> fix(core): fix #946, don't patch promise if it is not writable

lib/jasmine/jasmine.ts, lib/mocha/mocha.ts, lib/zone-spec/async-test.ts, lib/zone-spec/proxy.ts
when jasmine/mocha test case timeout, the message will be 
```
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```
It will a little difficult to know which one not finished.
in this PR, I record the `async task` information in `ProxyZone`, so when timeout, the error message will look like.
```
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
--Pendng async tasks are: [type: macroTask, source: setTimeout, args: {handleId:3,isPeriodic:false,delay:10000,args:[]}
```
=> feat(testing): can display pending tasks info when test timeout in jasmine/mocha

gulpfile.js, karma-dist.conf.js, lib/testing/async-testing.ts, lib/testing/fake-async.ts, lib/testing/zone-testing.ts, lib/zone-spec/proxy.ts, sauce.conf.js, test/zone-spec/async-test.spec.ts, test/zone-spec/fake-async-test.spec.ts, test/zone-spec/proxy.spec.ts, test/zone-spec/sync-test.spec.ts, test/zone-spec/task-tracking.spec.ts
move async and fakeAsync from angular/core/testing to zone.js/testing.
rename async to asyncTest.
The motivation is
currently in angular/core/testing, async/fakeAsync doesn't include any angular thing or feature, they use pure zone.js API, so I think those 2 functions should be in zone.js, and we can provide some API to let angular customize some behaviors, such as automatically call fixture.detectChanges when tick in fakeAsync or provide customizedfinishedCallbackofasyncTest`.
move those functions into zone.js can make zone.js to be a useful testing tool for other non-angular applications, they can also use zone.js to handle async unit-test.
it is easy to fix bugs, for example, this issue angular/angular#22448 need both zone.js and angular modify the code, it is difficult to manage …
=> feat(test): move async/fakeAsync from angular to zone.js

lib/zone-spec/fake-async-test.ts, test/test-env-setup-mocha.ts, test/zone-spec/fake-async-test.spec.ts
fix #1056 
FakeAsyncTestSpec scheduler should not return a `zero` timerId, it will break `rxjs6` or some library which will depends on the `timerId`.
=> fix(fakeAsync): fix #1056, fakeAsync timerId should not be zero

lib/testing/zone-testing.ts
sorry I forget to put the `async-test` and `fakeAsync` into bundles.
@mhevery , please review.
=> fix(test): add async/fakeAsync into zone-testing bundle

lib/jasmine/jasmine.ts, lib/zone-spec/fake-async-test.ts, test/test-env-setup-mocha.ts, test/zone-spec/fake-async-test.spec.ts
fix #1069.
fix #1071.
- in `fakeAsync`, now `Date` is monkey-patched with `FakeDate`, `FakeDate` should handle parameters in constructor correctly, such as `new Date(1995, 1)`, `new Date(0)`.
- should handle `Date.UTC()` in `fakeAsync` correctly
- should handle `Date.parse()` in `fakeAsync` correctly
@mhevery , sorry this is a regression bug, please review and please check should we cut a new release or not.
=> fix(test): fix #1069, FakeDate should handle constructor parameter

gulpfile.js, karma-base.conf.js, karma-dist-mocha.conf.js, karma-dist.conf.js, sauce-selenium3.conf.js, sauce.conf.js, test/browser-zone-setup.ts, test/browser/MediaQuery.spec.ts, test/browser/Notification.spec.ts, test/main.ts, test/node_entry_point.ts, test/test-env-setup-jasmine.ts, test/test-env-setup-mocha.ts, test/webdriver/test.sauce.js
current `karma-dist.conf.js` will load bundles under `dist` and the purpose is to test those built bundles instead of the dev version which under `build` folder.
so in `karma-dist.conf.js`, we will load 
```javascript
config.files.push('dist/zone.js');
config.files.push('dist/async-test.js');
...
``` 
But in current test cases will load some of the lib directly from `build` folder, for example in `async-test.spec.ts`, in current version, it will load 
```javascript
import '../../lib/zone-spec/async-test';
```
so the test case in fact will not test the bundle under `dist` but `build`.
-------------
in this PR, I load all needed bundles in `karma-dist.conf.js` and remove all directly import from test specs. And also modify the test entry classes to make sure currently test cases will be ok …
=> fix(test): karma-dist should test bundle under dist

lib/browser/browser.ts, test/browser/XMLHttpRequest.spec.ts
fix https://github.com/angular/angular/issues/20921
fix https://github.com/angular/angular/issues/17192
currently `zone.js` patch `xhr` as a `macroTask` and after `xhr.send`, `zone.js` will add a `readystatechange` listener, when `readystate=4`, the `macroTask` will be invoked.
this logic work fine, but because `xhr` can also add `onload` or `addEventListener('load', listener)`.
and the `load` event handler will run after `readystatechange`, so in the `load` event handler, the zone may have been stabled, and cause some issues. such as in https://github.com/angular/angular/issues/20921, the `chained http` will trigger multiple `zone.stable`, and https://github.com/angular/angular/issues/17192, the onload will run outside of fixture.whenStable.
So in this PR, I just make sure all `onload` …
=> fix(xhr): should invoke xhr task after onload is triggered

README.md, SAMPLE.md
add current samples to `stackblitz` so it can run in browser directly.
And I will add more samples of `zone.js` built in spec samples in this way.
=> doc(sample): add samples to stackblitz

lib/zone.ts
fix #1078 
In some old browser or other environment, `Promise.prototype.then` may not configurable, so we should use `promise.then` instead of `promise['__zone_symbol__then']`.
=> fix(core): use then directly when promise is not patchable

.travis.yml, lib/common/utils.ts, lib/node/node.ts, lib/node/node_util.ts, package.json, test/node/fs.spec.ts, test/node/timer.spec.ts, test/node_tests.ts, yarn.lock
fix #1094 
the error can be described as this,
```javascript
import * as util from 'util';
const promisifyExists = util.promisify(exists);
promisifyExists(__filename).then(r => {
expect(r).toBe(true);
done();
}, err => {
fail(`should not be here with error: ${err}`);
});
```
Before this PR, after `promisify`, the promise will be `rejected` as error.
The reason is in `nodejs promisify` implementation, by default, it will handle the nodejs style callback `(err, ...values)` to promise, but some of the nodejs API is not in this style, such as `fs.exists`, the callback is `(exists) => {}`, without the 1st `err` parameter. 
So `nodejs` provide a mechanism to let those special API provide their own `promisify` implementation by add a `symbol property Symbol(custom)` in the method, for example, …
=> fix(node): node patched method should copy original delegate's symbol properties

.travis.yml, MODULE.md, file-size-limit.json, gulpfile.js, karma-base.conf.js, karma-build.conf.js, lib/browser/define-property.ts, lib/common/error-rewrite.ts, lib/common/utils.ts, lib/node/node_util.ts, package.json, sauce-selenium3.conf.js, sauce.conf.js, test/browser/WebSocket.spec.ts, test/common/Error.spec.ts, test/main.ts, test/node/fs.spec.ts, test/node/timer.spec.ts, test/node_entry_point.ts, test/node_error_entry_point.ts, test/webdriver/test.sauce.js, yarn.lock
fix #975.
current `zone-error` provide several functionality.
1. handle `class MyError extends Error`, `new MyError() instanceof Error` will report `false` issue. 
2. remove `zone.js internal stack trace frames`.
3. add `zone` information to each `zone frame`.
The No2 and No3. feature  will slow down the ` new Error()` performance, 
So the motivation of this PR is to provide a flag to let user be able to disable No2 and No3.
The flag is `__Zone_Error_BlacklistedStackFrames_policy`. And the available options is:
1. default: this is the default one, if you load `zone.js/dist/zone-error` without
setting the flag, `default` will be used, and `BlackListStackFrames` will be available 
when `new Error()`, you can get a `error.stack`  which is `zone stack free`. But this 
will slow down `new …
=> feat(error): fix #975, can config how to load blacklist zone stack frames

lib/zone.ts
fix #910.
add a flag, `__zone_symbol__forceDuplicateZoneCheck` to let user choose whether to throw `error` when load `duplicate` zone.js.
By default, if the `global['Zone']` is from `zone.js`, no error will be thrown, and if the `flag` is set to `trure`, then we will throw the error.
sometimes user may not want this `Zone already loaded` error.
For example,
we have two web pages, page1 includes `zone.js`, page2 doesn't.
and the 1st time user load page1 and page2, everything work fine,
but when user load page2 again, error occurs because global['Zone'] already exists.
so we add a flag to let user choose whether to throw this error or not.
=> feat(Core): fix #910, add a flag to allow user to check duplicate Zone error.

file-size-limit.json, lib/browser/browser.ts, test/browser/XMLHttpRequest.spec.ts
fix #1072.
- it is better to set `scheduled` flag to `target` than `XMLHttpRequest`.  set to `XMLHttpRequest` is not a bug, but is not a good way to set such kind of `flag` to global object.
- issue #530, when open an invalid request, current logic will leave a `scheduled macroTask` in `chrome`. we should `invoke` the task to make the `macroTask` finish.
```javascript
var req = new XMLHttpRequest();
req.open('get', 'file:///test', true);
req.send();
```
=> fix(xhr): fix #1072, should set scheduled flag to target

lib/common/utils.ts
This is related to https://github.com/angular/angular/issues/24048#issuecomment-395099543
As JSDOM shares prototypes we have a leak after directly patching them.
The proposed solution is to wrap global functions with delegators and also their prototypes same way.
This way zone.js will patch only delegators making originals untouched and no memory leak therefore will hapen.
In order to reproduce the issue please refer to https://github.com/FreeleX/jest-angular-memory-leak-example and for more info to the https://github.com/angular/angular/issues/24048
=> fix(memory): reduce memory leaks in Jest JSDOM environment

file-size-limit.json, lib/browser/property-descriptor.ts, lib/common/utils.ts, test/browser/browser.spec.ts, test/test-util.ts
Fix #1108,
Based on the document here, https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror#window.onerror
The signature  of `window.onerror`  should be 
```ts
window.onerror = function(message, source, lineno, colno, error) { ... }
```
And `window.addEventListener('error', listener)` should be 
```ts
window.addEventListener('error', function(event) { ... })
```
So we must handle the `onerror` special case.
=> fix(core): fix #1108, window.onerror should have (message, source, ....) signiture

file-size-limit.json, lib/common/promise.ts, lib/extra/bluebird.ts, test/extra/bluebird.spec.ts
fix #1112.
The issue can be described as the following case.
```ts
new BluebirdPromise((resolve: any, reject: any) => {
expect(Zone.current.name).toEqual('zone_A');
resolve(1);
}).then((r: any) => {
expect(r).toBe(1);
expect(Zone.current.name).toEqual('zone_A');
return Promise.resolve(2);
}).then((r: any) => {
expect(r).toBe(2);
expect(Zone.current.name).toEqual('zone_A');
});
```
So we should return a `new bluebird promise` in `then callback`.
=> fix(bluebird): fix #1112, bluebird chained callback should return a Bluebird Promise

lib/zone-spec/fake-async-test.ts, test/zone-spec/fake-async-test.spec.ts
In the case where there is pending work in the scheduler queue, but the duration
of the tick did not causes it to run the doTick callback would not be called (or
would not be called with intervals summing to the total time ellapsed).
=> Ensure FakeAsyncTestZoneSpec tick always doTick

lib/browser/property-descriptor.ts, package.json, yarn.lock
1. Upgrade to typescript 3.0.3
2. Add `resume`, `freeze` onProperty patch for `document` in `chrome 66`.
@mhevery, please review. thanks!
=> feat(core): upgrade to typescript 3.0.3

lib/browser/property-descriptor.ts
Avoid closure renaming while accessing the global symbol.
=> fix(onProperty): user quoted access for __Zone_ignore_on_properties

lib/common/promise.ts
For ZoneAwarePromise.all, as [implemented](https://github.com/angular/zone.js/blob/7201d44451f6c67eac2b86eca3cbfafde14035d6/lib/common/promise.ts), the `count` variable serves three purposes:
1.  Count the number of values passed-in
2.  Specify the index of a resolved value in `resolvedValues`
3.  Track when all the promises have been resolved.
In the event that `value.then` is immediately called, `count` will be decremented at the incorrect time resulting in a potentially negative value or reaching 0 when not all values have actually been resolved. 
The fix is to be more meticulous about using the correct indices at the correct time and to not overload the count and number of resolved promises.  This updated version is more explicit about the purpose of the `unresolvedCount` and …
=> Fix ZoneAwarePromise.all to resolve at the correct time

.travis.yml, lib/common/events.ts, test/node/events.spec.ts, yarn.lock
fix #1164.
in `nodejs 10`, there is a logic in `domain.js`.
```
process.on('newListener', (name, listener) => {
if (name === 'uncaughtException' &&
listener !== domainUncaughtExceptionClear) {
// Make sure the first listener for `uncaughtException` always clears
// the domain stack.
process.removeListener(name, domainUncaughtExceptionClear);
process.prependListener(name, domainUncaughtExceptionClear);
}
});
```
here ` listener !== domainUncaughtExceptionClear` will crash `zone`, because `listener` will be `zoneTask.invoke` instead of the original listener.
So this PR will just `bypass` `uncaughtException`.
------------
also update the `travis CI` to `nodejs 10`, to make `nodejs 10` work, I updated `yarn.lock` to update `natives to 1.1.3`, otherwise `gulp` will not work. …
=> fix(node): fix #1164, don't patch uncaughtException to prevent endless loop.

lib/zone.ts, test/common/toString.spec.ts
=> fix(core): fix #1153, ZoneTask.toString should always be a string

lib/zone.ts
This issue is posted by @vsavkin from slack, in one project using `angularjs 1.X ngUpgrade with Angular5`,  in `Edge`, the `setInterval` will still call `runTask` after `cancelInterval`, cannot reproduce with a simple project. There is the similar error before in #778, so in this PR, we will add some code to prevent such kind of error.
@mhevery, please review.
=> fix(core): fix interval will still run after cancelled error

file-size-limit.json, lib/common/events.ts, lib/node/events.ts, test/node/events.spec.ts, tsconfig-esm-node.json, tsconfig-esm.json, tsconfig-node.json, tsconfig.json
fix #1110.
In nodejs, `EventEmitter` should support `Symbol` as `eventName`.
```ts
const symbolA = Symbol('A');
emitter.addListener(symbolA, listener);
emitter.removeListener(symbolA, listener);
```
=> fix(event): fix #1110, nodejs EventEmitter should support Symbol eventName

lib/zone.ts
fix #1081, `__load_patch` should also check `duplicate flag`. 
So when we load `zone.js` multiple times, it will not throw `ZoneAwarePromise already been patched` error.
=> fix(duplicate): fix #1081, load patch should also check the duplicate flag

lib/browser/register-element.ts
To pass test in `angular`, we need to handle some of `callbacks` are not implemented by some `polyfilles`. `@webcomponent/native_shim.js` doesn't implement `adopdatedCallback`, `zone.js` will throw error, so we need to check this case.
=> fix(element): Fix native_shim.js not implement adoptedCallback error.

lib/jasmine/jasmine.ts, package.json, test/node_bluebird_entry_point.ts, yarn.lock
jasmine 3.3 will ignore `process.unhandledRejection eventListeners`, so some of our `Promise test` will fail, in this PR, I restore the `process.unhandledRejection` to make our test pass.
=> build: upgrade to pass jasmine 3.3 test

lib/browser/api-util.ts, lib/browser/browser-legacy.ts, lib/browser/browser.ts, test/test_fake_polyfill.ts
based on this change in Angular repo, https://github.com/angular/angular/pull/28529
change env name from `__zone_symbol__BLACK_LISTED_EVENTS` to `__zone_symbol__DISABLE_EVENTS`.
And for `backward compatibility`, we still support `__zone_symbol__BLACK_LISTED_EVENTS`
=> env: change BLACK_LISTED_EVENTS to DISABLE_EVENTS

lib/zone.ts
Change the word TimerTask to MacroTask to maintain the consistency of terminology.
=> docs: change the word TimerTask to MacroTask

MODULE.md
The source code lib/browser.ts says that the correct property to disable timer patching name is **timers** not **timer**.
=> Fix the typo in timer module documentation

test/performance/eventTarget.js, test/performance/performance.html, test/performance/performance_setup.js, test/performance/performance_ui.js, test/performance/promise.js, test/performance/requestAnimationFrame.js, test/performance/timeout.js, test/performance/xhr.js
add benchmark page to measure the performance gap between `zone.js` patched and `native` API.
this is still working in progress.
the result looks like this.
=> Perf(test): add benchmark page

test/common/Promise.spec.ts
add test cases for #1150, `Promise.all` should handle `sync thenable` operations.
=> test(promise): add test cases for Promise.all with sync then operations

lib/jasmine/jasmine.ts, lib/mocha/mocha.ts
fix #1155.
In some test cases, the user may throw an error with an unconfigurable or readonly `message` property, so we should try/catch when we want to add some additional information to the message there.
=> fix(test): fix #1155, try/catch modify error.message

file-size-limit.json, lib/browser/api-util.ts, lib/browser/browser-legacy.ts, lib/browser/browser-util.ts, lib/browser/browser.ts, lib/browser/custom-elements.ts, lib/browser/define-property.ts, lib/browser/event-target-legacy.ts, lib/browser/event-target.ts, lib/browser/property-descriptor-legacy.ts, lib/browser/property-descriptor.ts, lib/browser/register-element.ts, lib/browser/websocket.ts, lib/common/utils.ts, lib/zone.ts, test/browser/WebSocket.spec.ts, test/zone_worker_entry_point.ts
In `angular cli`, there is a file named `es2015-polyfill.js`, inside this file, all `polyfill` for `es5 legacy browsers` will be there, so with `zone evergreen bundle`, the most idle way to handle this is.
1. put a `zone-legacy.js` inside `es2015-polyfill.js`.
2. put `zone-evergreen.js` inside `polyfill.ts`.
So 
1. in `es5 legacy browser`, it will load `zone-legacy.js` + `zone-evergreen.js`.
2. in `modern browser`, it will only load `zone-evergreen.js`.
Before this PR, `zone-legacy.js` need to be loaded after `zone-evergreen.js`, because  the `zone-legacy` use a lot of `common logic` from `zone-evergreen.js`. So in this PR,
1. `zone-legacy.js` is a `lazy load module` which will only define a `factory function`.
2. When `zone-evergreen.js` loading, it will check whether this `lazy load …
=> build: make legacy standalone bundle

lib/zone-spec/fake-async-test.ts
There is a possibility that a single test gets timer id-s from two
separate fakeAsync test zones and the id-s could clash.
This changes makes it such that the next timer id is global and the can
never clash.
=> fix: make fakeAsync test spec timer id global

lib/browser/event-target-legacy.ts, lib/browser/event-target.ts
If the event that EventTarget is defined on a device that also does not support patch via property descriptor, the result is that the XMLHttpRequest class would be patched prior to the event target being patched (due to returning in event-target-legacy if EventTarget is defined). This results in the wrapper that replaces XMLHttpRequest missing the patched listener fields. E.g. __zone_symbol__addEventListener and __zone_symbol__removeEventListener
event-target-legacy.
The result is that for any attempted http requests, a type error occurs in scheduleTask in browse.ts -> patchXhr, due to attempting call to non-existent __zone_symbol__addEventListener and  __zone_symbol__removeEventListener, causing the requests to fail.
Ensuring that patching of event target for legacy path takes place …
=> Ensure that EventTarget is patched prior to legacy property descriptor patch

lib/zone-spec/fake-async-test.ts, test/zone-spec/fake-async-test.spec.ts
=> fix: fakeAsyncTest requestAnimationFrame should pass timestamp as parameter

lib/jasmine/jasmine.ts, test/browser-zone-setup.ts, test/node_entry_point.ts, test/test-env-setup-jasmine-no-patch-clock.ts, test/zone-spec/fake-async-test.spec.ts
1. add an option `fakeAsyncDisablePatchingClock` to be able to disable `jasmine.clock patch`.
2. rename `fakeAsyncPatchLock` to `fakeAsyncAutoFakeAsyncWhenClockPatched` because the original name is confused.
3. if `fakeAsyncDisablePatchingClock` is true, should also make `fakeAsyncAutoFakeAsyncWhenClockPatched` to be `false`.
@vikerman, please review, thanks!
=> feat: add option to disable jasmine clock patch, also rename the flag of auto jump in FakeAsyncTest
